/* LostInWeb — Curated interesting websites
   Only real, working sites. Categories: tools, games, articles, weird, interactive, creative, science, art
*/
const SITES = [
  { url: "https://neal.fun/", title: "Neal.fun", desc: "Hub of polished browser experiments and interactive toys", cat: "interactive" },
  { url: "https://neal.fun/infinite-craft/", title: "Infinite Craft", desc: "Combine elements with AI to invent anything", cat: "games" },
  { url: "https://neal.fun/password-game/", title: "The Password Game", desc: "Create a password that meets absurd escalating rules", cat: "games" },
  { url: "https://neal.fun/deep-sea/", title: "The Deep Sea", desc: "Scroll into the ocean depths and meet its creatures", cat: "science" },
  { url: "https://neal.fun/spend/", title: "Spend Bill Gates' Money", desc: "Try to burn through a billion dollars on real products", cat: "games" },
  { url: "https://neal.fun/asteroid-launcher/", title: "Asteroid Launcher", desc: "Simulate asteroid impacts on real locations", cat: "science" },
  { url: "https://neal.fun/absurd-trolley-problems/", title: "Absurd Trolley Problems", desc: "Ethical dilemmas with increasingly ridiculous twists", cat: "interactive" },
  { url: "https://neal.fun/size-of-space/", title: "The Size of Space", desc: "Visualize the staggering scale of the universe", cat: "science" },
  { url: "https://neal.fun/internet-artifacts/", title: "Internet Artifacts", desc: "A museum of early web culture and forgotten interfaces", cat: "art" },
  { url: "https://neal.fun/stimulation-clicker/", title: "Stimulation Clicker", desc: "A clicker that parodies modern internet overload", cat: "games" },
  { url: "https://neal.fun/draw-a-perfect-circle/", title: "Draw a Perfect Circle", desc: "Test how steady your hand really is", cat: "games" },
  { url: "https://neal.fun/wonders-of-street-view/", title: "Wonders of Street View", desc: "Beautiful and strange places captured by Google", cat: "interactive" },
  { url: "https://neal.fun/space-elevator/", title: "Space Elevator", desc: "Ride an elevator from Earth into orbit", cat: "science" },
  { url: "https://neal.fun/life-stats/", title: "Life Stats", desc: "Real-time stats about your life so far", cat: "interactive" },
  { url: "https://neal.fun/progress/", title: "Progress", desc: "Visual progress bars for human civilization milestones", cat: "science" },
  { url: "https://theuselessweb.com/", title: "The Useless Web", desc: "One button sends you to a random pointless website", cat: "weird" },
  { url: "https://pointerpointer.com/", title: "Pointer Pointer", desc: "Photos of hands that always point at your cursor", cat: "weird" },
  { url: "https://cat-bounce.com/", title: "Cat Bounce", desc: "Bouncing cartoon cats. That’s the whole site", cat: "weird" },
  { url: "https://findtheinvisiblecow.com/", title: "Find the Invisible Cow", desc: "Hunt an invisible cow by sound alone", cat: "games" },
  { url: "https://hackertyper.com/", title: "Hacker Typer", desc: "Type anything and look like a movie hacker", cat: "weird" },
  { url: "https://zombo.com/", title: "Zombo.com", desc: "The classic 1999 infinite possibility loop", cat: "weird" },
  { url: "https://koalastothemax.com/", title: "Koalas to the Max", desc: "Reveal a hidden koala by hovering over circles", cat: "art" },
  { url: "https://zoomquilt.org/", title: "Zoomquilt", desc: "Infinitely zooming collaborative surreal painting", cat: "art" },
  { url: "https://thisissand.com/", title: "This Is Sand", desc: "Pour colorful digital sand into layered art", cat: "creative" },
  { url: "https://patatap.com/", title: "Patatap", desc: "Keyboard keys trigger unique animations and sounds", cat: "creative" },
  { url: "https://staggeringbeauty.com/", title: "Staggering Beauty", desc: "Wiggle your mouse and watch the worm dance", cat: "weird" },
  { url: "https://heeeeeeeey.com/", title: "Heeeeeeeey", desc: "Just an endless greeting", cat: "weird" },
  { url: "https://fallingfalling.com/", title: "Falling Falling", desc: "Colored bands fall forever", cat: "weird" },
  { url: "https://isitchristmas.com/", title: "Is It Christmas?", desc: "A definitive yes or no answer", cat: "weird" },
  { url: "https://eelslap.com/", title: "Eel Slap", desc: "Slap someone with an eel", cat: "weird" },
  { url: "https://radio.garden/", title: "Radio Garden", desc: "Spin a globe and listen to live radio anywhere", cat: "creative" },
  { url: "https://window-swap.com/", title: "WindowSwap", desc: "Look out of strangers’ windows around the world", cat: "interactive" },
  { url: "https://asoftmurmur.com/", title: "A Soft Murmur", desc: "Mix ambient sounds — rain, thunder, café noise", cat: "tools" },
  { url: "https://mynoise.net/", title: "myNoise", desc: "Highly customizable ambient soundscapes", cat: "tools" },
  { url: "https://rainymood.com/", title: "Rainy Mood", desc: "Endless rain sounds for focus or sleep", cat: "tools" },
  { url: "https://imissmycafe.com/", title: "I Miss My Café", desc: "Café ambience when you can’t go out", cat: "tools" },
  { url: "https://www.mapcrunch.com/", title: "MapCrunch", desc: "Random Google Street View location on Earth", cat: "interactive" },
  { url: "https://www.atlasobscura.com/", title: "Atlas Obscura", desc: "Curious and wondrous places around the world", cat: "articles" },
  { url: "https://earth.google.com/web/", title: "Google Earth", desc: "Explore the planet in 3D", cat: "science" },
  { url: "https://www.thetruesize.com/", title: "The True Size Of", desc: "Compare the real sizes of countries on a map", cat: "tools" },
  { url: "https://random.earth/", title: "Random Earth", desc: "Random spots as if viewed from the ISS", cat: "interactive" },
  { url: "https://orbis.stanford.edu/", title: "ORBIS", desc: "Travel routes and costs in the Roman world", cat: "science" },
  { url: "https://everynoise.com/", title: "Every Noise at Once", desc: "Vast map of music genres you can click and hear", cat: "creative" },
  { url: "https://radiooooo.com/", title: "Radiooooo", desc: "Pick a country and decade, then press play", cat: "creative" },
  { url: "https://incredibox.com/", title: "Incredibox", desc: "Create beatbox music by dragging sounds onto characters", cat: "creative" },
  { url: "https://musiclab.chromeexperiments.com/Song-Maker/", title: "Chrome Music Lab: Song Maker", desc: "Compose music by clicking a grid", cat: "creative" },
  { url: "https://blobopera.app/", title: "Blob Opera", desc: "Compose opera by moving cute animated blobs", cat: "creative" },
  { url: "https://www.geoguessr.com/", title: "GeoGuessr", desc: "Guess your location from Street View", cat: "games" },
  { url: "https://littlealchemy2.com/", title: "Little Alchemy 2", desc: "Combine elements to discover hundreds of items", cat: "games" },
  { url: "https://www.decisionproblem.com/paperclips/", title: "Universal Paperclips", desc: "Make paperclips… then question existence", cat: "games" },
  { url: "https://orteil.dashnet.org/cookieclicker/", title: "Cookie Clicker", desc: "The original idle cookie empire", cat: "games" },
  { url: "https://adarkroom.florianhimsl.com/", title: "A Dark Room", desc: "Minimal text adventure that expands into a world", cat: "games" },
  { url: "https://quickdraw.withgoogle.com/", title: "Quick, Draw!", desc: "Draw and let AI guess what it is", cat: "games" },
  { url: "https://www.thewikigame.com/", title: "The Wiki Game", desc: "Race between Wikipedia pages using only links", cat: "games" },
  { url: "https://onesquareminesweeper.com/", title: "One Square Minesweeper", desc: "Minesweeper with one square. 50/50 odds", cat: "games" },
  { url: "https://reallybadchess.com/", title: "Really Bad Chess", desc: "Chess with randomized, terrible piece setups", cat: "games" },
  { url: "https://sandspiel.club/", title: "Sandspiel", desc: "Falling-sand physics sandbox you can play in", cat: "games" },
  { url: "https://silk.genso.me/", title: "Silk", desc: "Create flowing generative art with your mouse", cat: "art" },
  { url: "https://www.jacksonpollock.org/", title: "Jackson Pollock", desc: "Drip paint like the abstract expressionist", cat: "art" },
  { url: "https://weavesilk.com/", title: "WeaveSilk", desc: "Symmetrical generative silk drawings", cat: "art" },
  { url: "https://www.chrometosphere.com/", title: "Chrometosphere", desc: "Interactive metallic particle playground", cat: "art" },
  { url: "https://ncase.me/", title: "Nicky Case", desc: "Explorable explanations and interactive essays", cat: "interactive" },
  { url: "https://ncase.me/trust/", title: "The Evolution of Trust", desc: "Interactive game theory about cooperation", cat: "interactive" },
  { url: "https://ncase.me/polygons/", title: "Parable of the Polygons", desc: "A playable story about bias and segregation", cat: "interactive" },
  { url: "https://htwins.net/scale2/", title: "Scale of the Universe 2", desc: "Zoom from quarks to galaxy clusters", cat: "science" },
  { url: "https://www.solarviews.com/eng/earth.htm", title: "Views of the Solar System", desc: "Classic planetary exploration resource", cat: "science" },
  { url: "https://eyes.nasa.gov/", title: "NASA Eyes", desc: "Real-time 3D views of spacecraft and planets", cat: "science" },
  { url: "https://stellarium-web.org/", title: "Stellarium Web", desc: "Interactive planetarium in your browser", cat: "science" },
  { url: "https://www.etymonline.com/", title: "Online Etymology Dictionary", desc: "Where words actually come from", cat: "tools" },
  { url: "https://www.gutenberg.org/", title: "Project Gutenberg", desc: "Tens of thousands of free classic books", cat: "articles" },
  { url: "https://archive.org/", title: "Internet Archive", desc: "The Wayback Machine and a library of everything", cat: "tools" },
  { url: "https://scholar.google.com/", title: "Google Scholar", desc: "Search academic papers and citations", cat: "tools" },
  { url: "https://www.wolframalpha.com/", title: "WolframAlpha", desc: "Computational knowledge engine", cat: "tools" },
  { url: "https://www.remove.bg/", title: "Remove.bg", desc: "Instantly remove image backgrounds with AI", cat: "tools" },
  { url: "https://photopea.com/", title: "Photopea", desc: "Full-featured image editor that runs in the browser", cat: "tools" },
  { url: "https://www.desmos.com/calculator", title: "Desmos", desc: "Beautiful free graphing calculator", cat: "tools" },
  { url: "https://excalidraw.com/", title: "Excalidraw", desc: "Virtual whiteboard for sketching diagrams", cat: "tools" },
  { url: "https://carbon.now.sh/", title: "Carbon", desc: "Create beautiful images of your source code", cat: "tools" },
  { url: "https://typelit.io/", title: "Typelit", desc: "Practice typing by retyping classic novels", cat: "tools" },
  { url: "https://www.omnieye.com/", title: "OmniEye", desc: "Live webcam feeds from around the world", cat: "interactive" },
  { url: "https://www.boredbutton.com/", title: "Bored Button", desc: "One click to a random activity or site", cat: "weird" },
  { url: "https://www.pointlesssites.com/", title: "Pointless Sites", desc: "Directory of wonderfully useless websites", cat: "weird" },
  { url: "https://noclip.website/", title: "Noclip", desc: "Fly through abandoned levels of old video games", cat: "interactive" },
  { url: "https://www.windows93.net/", title: "Windows 93", desc: "A surreal parody operating system in the browser", cat: "weird" },
  { url: "https://www.thequietplaceproject.com/thequietplace", title: "The Quiet Place", desc: "A space to write something and leave it behind", cat: "interactive" },
  { url: "https://www.drawastickman.com/", title: "Draw a Stickman", desc: "Interactive stickman adventure you draw yourself", cat: "games" },
  { url: "https://www.notpron.com/", title: "Notpron", desc: "One of the hardest online riddle games ever", cat: "games" },
  { url: "https://www.linusakesson.net/scene/longcat/", title: "Longcat", desc: "How long can a cat be?", cat: "weird" },
  { url: "https://www.rrrrrrrrr.com/", title: "Rrrrrrrrr", desc: "Just the letter R. Lots of it", cat: "weird" },
  { url: "https://www.omfgdogs.com/", title: "OMFG Dogs", desc: "Dogs spinning to a catchy tune", cat: "weird" },
  { url: "https://experiments.withgoogle.com/", title: "Google Experiments", desc: "Collection of creative coding experiments", cat: "creative" },
  { url: "https://threejs.org/examples/", title: "Three.js Examples", desc: "Stunning 3D demos built with WebGL", cat: "creative" },
  { url: "https://www.shadertoy.com/", title: "Shadertoy", desc: "Live-coding community for GPU shaders", cat: "creative" },
  { url: "https://codepen.io/trending", title: "CodePen Trending", desc: "Front-end experiments from the community", cat: "creative" },
  { url: "https://www.oldweb.today/", title: "Oldweb.today", desc: "Browse the web as it looked in different eras", cat: "interactive" },
  { url: "https://web.archive.org/", title: "Wayback Machine", desc: "Travel back in time through archived pages", cat: "tools" },
  { url: "https://www.homestarrunner.com/", title: "Homestar Runner", desc: "Classic flash-era cartoons that still delight", cat: "art" },
  { url: "https://en.wikipedia.org/wiki/Special:Random", title: "Random Wikipedia", desc: "Jump to a completely random article", cat: "articles" },
  { url: "https://en.wikipedia.org/wiki/Portal:Contents", title: "Wikipedia Portals", desc: "Structured entry points into human knowledge", cat: "articles" },
  { url: "https://www.wikipedia.org/", title: "Wikipedia", desc: "The free encyclopedia", cat: "articles" },
  { url: "https://archive.org/web/", title: "Wayback Machine", desc: "Travel through internet history", cat: "tools" },
  { url: "https://www.khanacademy.org/", title: "Khan Academy", desc: "Free world-class education", cat: "science" },
  { url: "https://www.desmos.com/calculator", title: "Desmos Graphing Calculator", desc: "Beautiful free graphing", cat: "tools" },
  { url: "https://www.figma.com/", title: "Figma", desc: "Collaborative interface design", cat: "tools" },
  { url: "https://obsidian.md/", title: "Obsidian", desc: "Linked thought knowledge base", cat: "tools" },
  { url: "https://www.are.na/", title: "Are.na", desc: "Calm idea collection", cat: "tools" },
  { url: "https://codepen.io/", title: "CodePen", desc: "Front-end playground", cat: "creative" },
  { url: "https://www.p5js.org/", title: "p5.js", desc: "Creative coding for artists", cat: "creative" },
  { url: "https://processing.org/", title: "Processing", desc: "Visual software sketchbook", cat: "creative" },
  { url: "https://www.openprocessing.org/", title: "OpenProcessing", desc: "Share creative coding sketches", cat: "creative" },
  { url: "https://www.itch.io/", title: "itch.io", desc: "Independent games", cat: "games" },
  { url: "https://www.freeindiegam.es/", title: "Free Indie Games", desc: "Curated free experimental games", cat: "games" },
  { url: "https://www.newgrounds.com/", title: "Newgrounds", desc: "Classic flash games and animation", cat: "games" },
  { url: "https://lichess.org/", title: "Lichess", desc: "Free open-source chess", cat: "games" },
  { url: "https://www.nytimes.com/games/wordle", title: "Wordle", desc: "Daily word puzzle", cat: "games" },
  { url: "https://www.nytimes.com/games/connections", title: "Connections", desc: "Group words by theme", cat: "games" },
  { url: "https://www.sudoku.com/", title: "Sudoku.com", desc: "Classic number puzzles", cat: "games" },
  { url: "https://www.sporcle.com/", title: "Sporcle", desc: "Trivia quizzes", cat: "games" },
  { url: "https://www.jetpunk.com/", title: "JetPunk", desc: "Geography and knowledge quizzes", cat: "games" },
  { url: "https://www.skribbl.io/", title: "Skribbl.io", desc: "Multiplayer drawing game", cat: "games" },
  { url: "https://garticphone.com/", title: "Gartic Phone", desc: "Telephone with drawings", cat: "games" },
  { url: "https://www.agar.io/", title: "Agar.io", desc: "Multiplayer blob game", cat: "games" },
  { url: "https://www.slither.io/", title: "Slither.io", desc: "Snake multiplayer", cat: "games" },
  { url: "https://www.krunker.io/", title: "Krunker.io", desc: "Browser FPS", cat: "games" },
  { url: "https://www.shellshock.io/", title: "Shell Shockers", desc: "Egg-themed shooter", cat: "games" },
  { url: "https://store.steampowered.com/explore/", title: "Steam Explore", desc: "Discover games", cat: "games" },
  { url: "https://www.gog.com/", title: "GOG", desc: "DRM-free games", cat: "games" },
  { url: "https://www.humblebundle.com/", title: "Humble Bundle", desc: "Pay-what-you-want bundles", cat: "games" },
  { url: "https://www.producthunt.com/", title: "Product Hunt", desc: "New tools daily", cat: "tools" },
  { url: "https://news.ycombinator.com/", title: "Hacker News", desc: "Tech discussion", cat: "articles" },
  { url: "https://lobste.rs/", title: "Lobsters", desc: "Computing links", cat: "articles" },
  { url: "https://www.metafilter.com/", title: "MetaFilter", desc: "Community weblog", cat: "articles" },
  { url: "https://www.boingboing.net/", title: "Boing Boing", desc: "Directory of wonderful things", cat: "articles" },
  { url: "https://kottke.org/", title: "Kottke.org", desc: "Interesting links and ideas", cat: "articles" },
  { url: "https://www.themarginalian.org/", title: "The Marginalian", desc: "Art, science, meaning", cat: "articles" },
  { url: "https://www.theatlantic.com/", title: "The Atlantic", desc: "Long-form journalism", cat: "articles" },
  { url: "https://www.newyorker.com/", title: "The New Yorker", desc: "Fiction and essays", cat: "articles" },
  { url: "https://www.lrb.co.uk/", title: "London Review of Books", desc: "Serious reviews", cat: "articles" },
  { url: "https://www.poetryfoundation.org/", title: "Poetry Foundation", desc: "Poems and poets", cat: "art" },
  { url: "https://www.loc.gov/", title: "Library of Congress", desc: "American memory", cat: "articles" },
  { url: "https://www.europeana.eu/", title: "Europeana", desc: "European cultural heritage", cat: "art" },
  { url: "https://www.rijksmuseum.nl/en", title: "Rijksmuseum", desc: "Dutch masters", cat: "art" },
  { url: "https://www.metmuseum.org/", title: "The Met", desc: "Metropolitan Museum", cat: "art" },
  { url: "https://www.moma.org/", title: "MoMA", desc: "Modern art", cat: "art" },
  { url: "https://www.nasa.gov/", title: "NASA", desc: "Space exploration", cat: "science" },
  { url: "https://www.esa.int/", title: "ESA", desc: "European Space Agency", cat: "science" },
  { url: "https://www.jpl.nasa.gov/", title: "NASA JPL", desc: "Planetary exploration", cat: "science" },
  { url: "https://www.noaa.gov/", title: "NOAA", desc: "Weather and oceans", cat: "science" },
  { url: "https://www.usgs.gov/", title: "USGS", desc: "Earth science", cat: "science" },
  { url: "https://web.dev/", title: "web.dev", desc: "Modern web guidance", cat: "tools" },
  { url: "https://developer.mozilla.org/", title: "MDN Web Docs", desc: "Web technology reference", cat: "tools" },
  { url: "https://www.css-tricks.com/", title: "CSS-Tricks", desc: "Practical CSS", cat: "tools" },
  { url: "https://www.smashingmagazine.com/", title: "Smashing Magazine", desc: "Web design articles", cat: "articles" },
  { url: "https://www.awwwards.com/", title: "Awwwards", desc: "Best of the web", cat: "art" },
  { url: "https://www.siteinspire.com/", title: "SiteInspire", desc: "Web design inspiration", cat: "art" },
  { url: "https://land-book.com/", title: "Land-book", desc: "Landing page inspiration", cat: "art" },
  { url: "https://www.behance.net/", title: "Behance", desc: "Creative portfolios", cat: "art" },
  { url: "https://dribbble.com/", title: "Dribbble", desc: "Design community", cat: "art" },
  { url: "https://www.artstation.com/", title: "ArtStation", desc: "Professional art", cat: "art" },
  { url: "https://www.deviantart.com/", title: "DeviantArt", desc: "Art community", cat: "art" },
  { url: "https://www.bandcamp.com/", title: "Bandcamp", desc: "Independent music", cat: "creative" },
  { url: "https://www.soundcloud.com/", title: "SoundCloud", desc: "Audio sharing", cat: "creative" },
  { url: "https://www.discogs.com/", title: "Discogs", desc: "Music database", cat: "creative" },
  { url: "https://www.last.fm/", title: "Last.fm", desc: "Music scrobbling", cat: "creative" },
  { url: "https://www.goodreads.com/", title: "Goodreads", desc: "Book recommendations", cat: "articles" },
  { url: "https://www.librarything.com/", title: "LibraryThing", desc: "Personal libraries", cat: "articles" },
  { url: "https://www.imdb.com/", title: "IMDb", desc: "Movies and TV", cat: "articles" },
  { url: "https://www.rottentomatoes.com/", title: "Rotten Tomatoes", desc: "Movie reviews", cat: "articles" },
  { url: "https://www.metacritic.com/", title: "Metacritic", desc: "Reviews aggregation", cat: "articles" },
  { url: "https://www.letterboxd.com/", title: "Letterboxd", desc: "Film social network", cat: "articles" },
  { url: "https://www.trakt.tv/", title: "Trakt", desc: "Track movies and shows", cat: "tools" },
  { url: "https://www.duolingo.com/", title: "Duolingo", desc: "Language learning", cat: "tools" },
  { url: "https://www.ankiweb.net/", title: "Anki", desc: "Spaced repetition", cat: "tools" },
  { url: "https://www.memrise.com/", title: "Memrise", desc: "Language and memory", cat: "tools" },
  { url: "https://www.quizlet.com/", title: "Quizlet", desc: "Flashcards and study", cat: "tools" },
  { url: "https://www.coursera.org/", title: "Coursera", desc: "Online courses", cat: "articles" },
  { url: "https://www.edx.org/", title: "edX", desc: "University courses", cat: "articles" },
  { url: "https://www.udemy.com/", title: "Udemy", desc: "Skill courses", cat: "articles" },
  { url: "https://www.skillshare.com/", title: "Skillshare", desc: "Creative classes", cat: "creative" },
  { url: "https://www.ted.com/", title: "TED", desc: "Ideas worth spreading", cat: "articles" },
  { url: "https://www.npr.org/", title: "NPR", desc: "Public radio and news", cat: "articles" },
  { url: "https://www.bbc.com/", title: "BBC", desc: "News and culture", cat: "articles" },
  { url: "https://www.theguardian.com/", title: "The Guardian", desc: "Independent journalism", cat: "articles" },
  { url: "https://www.reuters.com/", title: "Reuters", desc: "Global news", cat: "articles" },
  { url: "https://www.apnews.com/", title: "AP News", desc: "Associated Press", cat: "articles" },
  { url: "https://www.nature.com/", title: "Nature", desc: "Science journal", cat: "science" },
  { url: "https://www.scientificamerican.com/", title: "Scientific American", desc: "Science writing", cat: "science" },
  { url: "https://www.space.com/", title: "Space.com", desc: "Space news", cat: "science" },
  { url: "https://www.nationalgeographic.com/", title: "National Geographic", desc: "Exploration and science", cat: "science" },
  { url: "https://www.smithsonianmag.com/", title: "Smithsonian Magazine", desc: "History and culture", cat: "articles" },
  { url: "https://www.colossal.com/", title: "Colossal", desc: "Art and visual culture", cat: "art" },
  { url: "https://www.thisiscolossal.com/", title: "This Is Colossal", desc: "Art and design", cat: "art" },
  { url: "https://www.designboom.com/", title: "Designboom", desc: "Architecture and design", cat: "art" },
  { url: "https://www.dezeen.com/", title: "Dezeen", desc: "Architecture and interiors", cat: "art" },
  { url: "https://www.archdaily.com/", title: "ArchDaily", desc: "Architecture news", cat: "art" },
  { url: "https://www.ign.com/", title: "IGN", desc: "Games and entertainment", cat: "games" },
  { url: "https://www.polygon.com/", title: "Polygon", desc: "Games culture", cat: "games" },
  { url: "https://www.kotaku.com/", title: "Kotaku", desc: "Gaming news", cat: "games" },
  { url: "https://www.rockpapershotgun.com/", title: "Rock Paper Shotgun", desc: "PC gaming", cat: "games" },
  { url: "https://www.eurogamer.net/", title: "Eurogamer", desc: "Games journalism", cat: "games" },
  { url: "https://www.pcgamer.com/", title: "PC Gamer", desc: "PC games", cat: "games" },
  { url: "https://www.gamespot.com/", title: "GameSpot", desc: "Games reviews", cat: "games" },
  { url: "https://www.twitch.tv/", title: "Twitch", desc: "Live streaming", cat: "creative" },
  { url: "https://www.canva.com/", title: "Canva", desc: "Design tool", cat: "tools" },
  { url: "https://www.photopea.com/", title: "Photopea", desc: "Browser photo editor", cat: "tools" },
  { url: "https://www.tinypng.com/", title: "TinyPNG", desc: "Image compression", cat: "tools" },
  { url: "https://squoosh.app/", title: "Squoosh", desc: "Image optimizer", cat: "tools" },
  { url: "https://www.iloveimg.com/", title: "ILoveIMG", desc: "Image tools", cat: "tools" },
  { url: "https://www.ilovepdf.com/", title: "ILovePDF", desc: "PDF tools", cat: "tools" },
  { url: "https://www.smallpdf.com/", title: "Smallpdf", desc: "PDF converter", cat: "tools" },
  { url: "https://www.pdf24.org/", title: "PDF24", desc: "PDF tools", cat: "tools" },
  { url: "https://ray.so/", title: "Ray.so", desc: "Code image generator", cat: "tools" },
  { url: "https://www.tldraw.com/", title: "tldraw", desc: "Infinite canvas", cat: "tools" },
  { url: "https://www.draw.io/", title: "diagrams.net", desc: "Diagramming", cat: "tools" },
  { url: "https://www.miro.com/", title: "Miro", desc: "Collaborative whiteboard", cat: "tools" },
  { url: "https://www.whimsical.com/", title: "Whimsical", desc: "Flowcharts and wireframes", cat: "tools" },
  { url: "https://www.regex101.com/", title: "Regex101", desc: "Regex tester", cat: "tools" },
  { url: "https://jsonformatter.org/", title: "JSON Formatter", desc: "JSON tools", cat: "tools" },
  { url: "https://jwt.io/", title: "JWT.io", desc: "JWT debugger", cat: "tools" },
  { url: "https://www.caniuse.com/", title: "Can I Use", desc: "Browser support", cat: "tools" },
  { url: "https://www.w3schools.com/", title: "W3Schools", desc: "Web tutorials", cat: "tools" },
  { url: "https://www.freecodecamp.org/", title: "freeCodeCamp", desc: "Learn to code", cat: "tools" },
  { url: "https://www.codecademy.com/", title: "Codecademy", desc: "Interactive coding", cat: "tools" },
  { url: "https://www.theodinproject.com/", title: "The Odin Project", desc: "Full-stack curriculum", cat: "tools" },
  { url: "https://www.leetcode.com/", title: "LeetCode", desc: "Coding practice", cat: "games" },
  { url: "https://www.codewars.com/", title: "Codewars", desc: "Coding kata", cat: "games" },
  { url: "https://www.hackerrank.com/", title: "HackerRank", desc: "Coding challenges", cat: "games" },
  { url: "https://www.adventofcode.com/", title: "Advent of Code", desc: "December puzzles", cat: "games" },
  { url: "https://projecteuler.net/", title: "Project Euler", desc: "Math programming", cat: "games" },
  { url: "https://www.replit.com/", title: "Replit", desc: "Browser coding", cat: "tools" },
  { url: "https://jsfiddle.net/", title: "JSFiddle", desc: "JS playground", cat: "tools" },
  { url: "https://www.observablehq.com/", title: "Observable", desc: "Reactive notebooks", cat: "science" },
  { url: "https://d3js.org/", title: "D3.js", desc: "Data visualization", cat: "creative" },
  { url: "https://www.redblobgames.com/", title: "Red Blob Games", desc: "Algorithm explanations", cat: "science" },
  { url: "https://visualgo.net/", title: "VisuAlgo", desc: "Algorithm visualizer", cat: "science" },
  { url: "https://algorithm-visualizer.org/", title: "Algorithm Visualizer", desc: "Interactive algorithms", cat: "science" },
  { url: "https://www.cs.usfca.edu/~galles/visualization/", title: "Data Structure Visualizations", desc: "Watch algorithms", cat: "science" },
  { url: "https://www.iquilezles.org/", title: "Inigo Quilez", desc: "Shader and math", cat: "science" },
];

const DEEPER_SITES = [
  { url: "https://www.windows93.net/", title: "Windows 93", desc: "A surreal parody operating system", cat: "weird" },
  { url: "https://www.notpron.com/", title: "Notpron", desc: "Extremely hard online riddle", cat: "games" },
  { url: "https://www.linusakesson.net/scene/longcat/", title: "Longcat", desc: "How long can a cat be?", cat: "weird" },
  { url: "https://www.rrrrrrrrr.com/", title: "Rrrrrrrrr", desc: "Just the letter R", cat: "weird" },
  { url: "https://www.omfgdogs.com/", title: "OMFG Dogs", desc: "Spinning dogs", cat: "weird" },
  { url: "https://heeeeeeeey.com/", title: "Heeeeeeeey", desc: "Endless greeting", cat: "weird" },
  { url: "https://fallingfalling.com/", title: "Falling Falling", desc: "Bands fall forever", cat: "weird" },
  { url: "https://eelslap.com/", title: "Eel Slap", desc: "Slap with an eel", cat: "weird" },
  { url: "https://staggeringbeauty.com/", title: "Staggering Beauty", desc: "Wiggling worm", cat: "weird" },
  { url: "https://cat-bounce.com/", title: "Cat Bounce", desc: "Bouncing cats", cat: "weird" },
  { url: "https://pointerpointer.com/", title: "Pointer Pointer", desc: "Hands point at your cursor", cat: "weird" },
  { url: "https://zombo.com/", title: "Zombo.com", desc: "1999 infinite possibility", cat: "weird" },
  { url: "https://hackertyper.com/", title: "Hacker Typer", desc: "Look like a movie hacker", cat: "weird" },
  { url: "https://findtheinvisiblecow.com/", title: "Find the Invisible Cow", desc: "Hunt by sound", cat: "games" },
  { url: "https://onesquareminesweeper.com/", title: "One Square Minesweeper", desc: "50/50 odds", cat: "games" },
  { url: "https://reallybadchess.com/", title: "Really Bad Chess", desc: "Terrible randomized setups", cat: "games" },
  { url: "https://www.thequietplaceproject.com/thequietplace", title: "The Quiet Place", desc: "Write and leave something behind", cat: "interactive" },
  { url: "https://noclip.website/", title: "Noclip", desc: "Fly through old game levels", cat: "interactive" },
  { url: "https://www.boredbutton.com/", title: "Bored Button", desc: "Random activity", cat: "weird" },
  { url: "https://www.pointlesssites.com/", title: "Pointless Sites", desc: "Wonderfully useless websites", cat: "weird" },
  { url: "https://www.omnieye.com/", title: "OmniEye", desc: "Live webcams worldwide", cat: "interactive" },
  { url: "https://window-swap.com/", title: "WindowSwap", desc: "Strangers’ windows", cat: "interactive" },
  { url: "https://radio.garden/", title: "Radio Garden", desc: "Live radio from anywhere", cat: "creative" },
  { url: "https://everynoise.com/", title: "Every Noise at Once", desc: "Map of music genres", cat: "creative" },
  { url: "https://radiooooo.com/", title: "Radiooooo", desc: "Country + decade radio", cat: "creative" },
  { url: "https://incredibox.com/", title: "Incredibox", desc: "Beatbox with characters", cat: "creative" },
  { url: "https://blobopera.app/", title: "Blob Opera", desc: "Opera with blobs", cat: "creative" },
  { url: "https://patatap.com/", title: "Patatap", desc: "Keyboard animations and sounds", cat: "creative" },
  { url: "https://thisissand.com/", title: "This Is Sand", desc: "Digital sand art", cat: "creative" },
  { url: "https://zoomquilt.org/", title: "Zoomquilt", desc: "Infinite surreal zoom", cat: "art" },
];

const CATEGORIES = ["all", "tools", "games", "articles", "weird", "interactive", "creative", "science", "art"];

const LOADING_PHRASES = [
  "Diving into the void…",
  "Finding something weird…",
  "Hope you brought a map",
  "Opening a random door…",
  "The algorithm is curious",
  "Somewhere on the web…",
  "Hold on to your bookmarks",
  " entangling with the internet",
  "A soft glitch in the matrix",
  "Fetching a rabbit hole",
  "This one might be strange",
  "Curating chaos…",
  "Almost lost…",
  "The void is responding",
  "One more click into the unknown",
];
