/* LostInWeb — Curated interesting websites (2025–2026 alive)
   Categories: tools, games, articles, weird, interactive, creative, science, art
*/
const SITES = [
  { url: "https://neal.fun/", title: "Neal.fun", desc: "Hub of polished browser experiments and interactive toys", cat: "interactive" },
  { url: "https://neal.fun/infinite-craft/", title: "Infinite Craft", desc: "Combine elements with AI to invent anything", cat: "games" },
  { url: "https://neal.fun/password-game/", title: "The Password Game", desc: "Create a password that meets absurd escalating rules", cat: "games" },
  { url: "https://neal.fun/deep-sea/", title: "The Deep Sea", desc: "Scroll into the ocean depths and meet its creatures", cat: "science" },
  { url: "https://neal.fun/spend/", title: "Spend Bill Gates' Money", desc: "Try to burn through a billion dollars on real products", cat: "games" },
  { url: "https://neal.fun/asteroid-launcher/", title: "Asteroid Launcher", desc: "Simulate asteroid impacts on real locations", cat: "science" },
  { url: "https://neal.fun/absurd-trolley-problems/", title: "Absurd Trolley Problems", desc: "Ethical dilemmas with increasingly ridiculous twists", cat: "interactive" },
  { url: "https://neal.fun/size-of-space/", title: "The Size of Space", desc: "Visualize the staggering scale of the universe", cat: "science" },
  { url: "https://neal.fun/internet-artifacts/", title: "Internet Artifacts", desc: "A museum of early web culture and forgotten interfaces", cat: "art" },
  { url: "https://neal.fun/stimulation-clicker/", title: "Stimulation Clicker", desc: "A clicker that parodies modern internet overload", cat: "games" },
  { url: "https://neal.fun/draw-a-perfect-circle/", title: "Draw a Perfect Circle", desc: "Test how steady your hand really is", cat: "games" },
  { url: "https://neal.fun/wonders-of-street-view/", title: "Wonders of Street View", desc: "Beautiful and strange places captured by Google", cat: "interactive" },
  { url: "https://neal.fun/space-elevator/", title: "Space Elevator", desc: "Ride an elevator from Earth into orbit", cat: "science" },
  { url: "https://neal.fun/life-stats/", title: "Life Stats", desc: "Real-time stats about your life so far", cat: "interactive" },
  { url: "https://neal.fun/progress/", title: "Progress", desc: "Visual progress bars for human civilization milestones", cat: "science" },
  { url: "https://theuselessweb.com/", title: "The Useless Web", desc: "One button sends you to a random pointless website", cat: "weird" },
  { url: "https://pointerpointer.com/", title: "Pointer Pointer", desc: "Photos of hands that always point at your cursor", cat: "weird" },
  { url: "https://cat-bounce.com/", title: "Cat Bounce", desc: "Bouncing cartoon cats. That’s the whole site", cat: "weird" },
  { url: "https://findtheinvisiblecow.com/", title: "Find the Invisible Cow", desc: "Hunt an invisible cow by sound alone", cat: "games" },
  { url: "https://hackertyper.com/", title: "Hacker Typer", desc: "Type anything and look like a movie hacker", cat: "weird" },
  { url: "https://zombo.com/", title: "Zombo.com", desc: "The classic 1999 infinite possibility loop", cat: "weird" },
  { url: "https://koalastothemax.com/", title: "Koalas to the Max", desc: "Reveal a hidden koala by hovering over circles", cat: "art" },
  { url: "https://zoomquilt.org/", title: "Zoomquilt", desc: "Infinitely zooming collaborative surreal painting", cat: "art" },
  { url: "https://thisissand.com/", title: "This Is Sand", desc: "Pour colorful digital sand into layered art", cat: "creative" },
  { url: "https://patatap.com/", title: "Patatap", desc: "Keyboard keys trigger unique animations and sounds", cat: "creative" },
  { url: "https://staggeringbeauty.com/", title: "Staggering Beauty", desc: "Wiggle your mouse and watch the worm dance", cat: "weird" },
  { url: "https://heeeeeeeey.com/", title: "Heeeeeeeey", desc: "Just an endless greeting", cat: "weird" },
  { url: "https://fallingfalling.com/", title: "Falling Falling", desc: "Colored bands fall forever", cat: "weird" },
  { url: "https://isitchristmas.com/", title: "Is It Christmas?", desc: "A definitive yes or no answer", cat: "weird" },
  { url: "https://eelslap.com/", title: "Eel Slap", desc: "Slap someone with an eel", cat: "weird" },
  { url: "https://radio.garden/", title: "Radio Garden", desc: "Spin a globe and listen to live radio anywhere", cat: "creative" },
  { url: "https://window-swap.com/", title: "WindowSwap", desc: "Look out of strangers’ windows around the world", cat: "interactive" },
  { url: "https://asoftmurmur.com/", title: "A Soft Murmur", desc: "Mix ambient sounds — rain, thunder, café noise", cat: "tools" },
  { url: "https://mynoise.net/", title: "myNoise", desc: "Highly customizable ambient soundscapes", cat: "tools" },
  { url: "https://rainymood.com/", title: "Rainy Mood", desc: "Endless rain sounds for focus or sleep", cat: "tools" },
  { url: "https://imissmycafe.com/", title: "I Miss My Café", desc: "Café ambience when you can’t go out", cat: "tools" },
  { url: "https://www.mapcrunch.com/", title: "MapCrunch", desc: "Random Google Street View location on Earth", cat: "interactive" },
  { url: "https://www.atlasobscura.com/", title: "Atlas Obscura", desc: "Curious and wondrous places around the world", cat: "articles" },
  { url: "https://earth.google.com/web/", title: "Google Earth", desc: "Explore the planet in 3D", cat: "science" },
  { url: "https://www.thetruesize.com/", title: "The True Size Of", desc: "Compare the real sizes of countries on a map", cat: "tools" },
  { url: "https://random.earth/", title: "Random Earth", desc: "Random spots as if viewed from the ISS", cat: "interactive" },
  { url: "https://orbis.stanford.edu/", title: "ORBIS", desc: "Travel routes and costs in the Roman world", cat: "science" },
  { url: "https://everynoise.com/", title: "Every Noise at Once", desc: "Vast map of music genres you can click and hear", cat: "creative" },
  { url: "https://radiooooo.com/", title: "Radiooooo", desc: "Pick a country and decade, then press play", cat: "creative" },
  { url: "https://incredibox.com/", title: "Incredibox", desc: "Create beatbox music by dragging sounds onto characters", cat: "creative" },
  { url: "https://musiclab.chromeexperiments.com/Song-Maker/", title: "Chrome Music Lab: Song Maker", desc: "Compose music by clicking a grid", cat: "creative" },
  { url: "https://blobopera.app/", title: "Blob Opera", desc: "Compose opera by moving cute animated blobs", cat: "creative" },
  { url: "https://www.geoguessr.com/", title: "GeoGuessr", desc: "Guess your location from Street View", cat: "games" },
  { url: "https://littlealchemy2.com/", title: "Little Alchemy 2", desc: "Combine elements to discover hundreds of items", cat: "games" },
  { url: "https://www.decisionproblem.com/paperclips/", title: "Universal Paperclips", desc: "Make paperclips… then question existence", cat: "games" },
  { url: "https://orteil.dashnet.org/cookieclicker/", title: "Cookie Clicker", desc: "The original idle cookie empire", cat: "games" },
  { url: "https://adarkroom.florianhimsl.com/", title: "A Dark Room", desc: "Minimal text adventure that expands into a world", cat: "games" },
  { url: "https://quickdraw.withgoogle.com/", title: "Quick, Draw!", desc: "Draw and let AI guess what it is", cat: "games" },
  { url: "https://www.thewikigame.com/", title: "The Wiki Game", desc: "Race between Wikipedia pages using only links", cat: "games" },
  { url: "https://onesquareminesweeper.com/", title: "One Square Minesweeper", desc: "Minesweeper with one square. 50/50 odds", cat: "games" },
  { url: "https://reallybadchess.com/", title: "Really Bad Chess", desc: "Chess with randomized, terrible piece setups", cat: "games" },
  { url: "https://sandspiel.club/", title: "Sandspiel", desc: "Falling-sand physics sandbox you can play in", cat: "games" },
  { url: "https://silk.genso.me/", title: "Silk", desc: "Create flowing generative art with your mouse", cat: "art" },
  { url: "https://www.jacksonpollock.org/", title: "Jackson Pollock", desc: "Drip paint like the abstract expressionist", cat: "art" },
  { url: "https://weavesilk.com/", title: "WeaveSilk", desc: "Symmetrical generative silk drawings", cat: "art" },
  { url: "https://www.chrometosphere.com/", title: "Chrometosphere", desc: "Interactive metallic particle playground", cat: "art" },
  { url: "https://ncase.me/", title: "Nicky Case", desc: "Explorable explanations and interactive essays", cat: "interactive" },
  { url: "https://ncase.me/trust/", title: "The Evolution of Trust", desc: "Interactive game theory about cooperation", cat: "interactive" },
  { url: "https://ncase.me/polygons/", title: "Parable of the Polygons", desc: "A playable story about bias and segregation", cat: "interactive" },
  { url: "https://htwins.net/scale2/", title: "Scale of the Universe 2", desc: "Zoom from quarks to galaxy clusters", cat: "science" },
  { url: "https://www.solarviews.com/eng/earth.htm", title: "Views of the Solar System", desc: "Classic planetary exploration resource", cat: "science" },
  { url: "https://eyes.nasa.gov/", title: "NASA Eyes", desc: "Real-time 3D views of spacecraft and planets", cat: "science" },
  { url: "https://stellarium-web.org/", title: "Stellarium Web", desc: "Interactive planetarium in your browser", cat: "science" },
  { url: "https://www.etymonline.com/", title: "Online Etymology Dictionary", desc: "Where words actually come from", cat: "tools" },
  { url: "https://www.gutenberg.org/", title: "Project Gutenberg", desc: "Tens of thousands of free classic books", cat: "articles" },
  { url: "https://archive.org/", title: "Internet Archive", desc: "The Wayback Machine and a library of everything", cat: "tools" },
  { url: "https://scholar.google.com/", title: "Google Scholar", desc: "Search academic papers and citations", cat: "tools" },
  { url: "https://www.wolframalpha.com/", title: "WolframAlpha", desc: "Computational knowledge engine", cat: "tools" },
  { url: "https://www.remove.bg/", title: "Remove.bg", desc: "Instantly remove image backgrounds with AI", cat: "tools" },
  { url: "https://photopea.com/", title: "Photopea", desc: "Full-featured image editor that runs in the browser", cat: "tools" },
  { url: "https://www.desmos.com/calculator", title: "Desmos", desc: "Beautiful free graphing calculator", cat: "tools" },
  { url: "https://excalidraw.com/", title: "Excalidraw", desc: "Virtual whiteboard for sketching diagrams", cat: "tools" },
  { url: "https://carbon.now.sh/", title: "Carbon", desc: "Create beautiful images of your source code", cat: "tools" },
  { url: "https://typelit.io/", title: "Typelit", desc: "Practice typing by retyping classic novels", cat: "tools" },
  { url: "https://www.omnieye.com/", title: "OmniEye", desc: "Live webcam feeds from around the world", cat: "interactive" },
  { url: "https://www.boredbutton.com/", title: "Bored Button", desc: "One click to a random activity or site", cat: "weird" },
  { url: "https://www.pointlesssites.com/", title: "Pointless Sites", desc: "Directory of wonderfully useless websites", cat: "weird" },
  { url: "https://noclip.website/", title: "Noclip", desc: "Fly through abandoned levels of old video games", cat: "interactive" },
  { url: "https://www.windows93.net/", title: "Windows 93", desc: "A surreal parody operating system in the browser", cat: "weird" },
  { url: "https://www.thequietplaceproject.com/thequietplace", title: "The Quiet Place", desc: "A space to write something and leave it behind", cat: "interactive" },
  { url: "https://www.drawastickman.com/", title: "Draw a Stickman", desc: "Interactive stickman adventure you draw yourself", cat: "games" },
  { url: "https://www.notpron.com/", title: "Notpron", desc: "One of the hardest online riddle games ever", cat: "games" },
  { url: "https://www.linusakesson.net/scene/longcat/", title: "Longcat", desc: "How long can a cat be?", cat: "weird" },
  { url: "https://www.rrrrrrrrr.com/", title: "Rrrrrrrrr", desc: "Just the letter R. Lots of it", cat: "weird" },
  { url: "https://www.omfgdogs.com/", title: "OMFG Dogs", desc: "Dogs spinning to a catchy tune", cat: "weird" },
  { url: "https://experiments.withgoogle.com/", title: "Google Experiments", desc: "Collection of creative coding experiments", cat: "creative" },
  { url: "https://chrome.google.com/webstore/category/collection/web_experiments", title: "Chrome Experiments", desc: "Pushing the limits of the browser", cat: "creative" },
  { url: "https://threejs.org/examples/", title: "Three.js Examples", desc: "Stunning 3D demos built with WebGL", cat: "creative" },
  { url: "https://www.shadertoy.com/", title: "Shadertoy", desc: "Live-coding community for GPU shaders", cat: "creative" },
  { url: "https://codepen.io/trending", title: "CodePen Trending", desc: "Front-end experiments from the community", cat: "creative" },
  { url: "https://www.oldweb.today/", title: "Oldweb.today", desc: "Browse the web as it looked in different eras", cat: "interactive" },
  { url: "https://web.archive.org/", title: "Wayback Machine", desc: "Travel back in time through archived pages", cat: "tools" },
  { url: "https://www.homestarrunner.com/", title: "Homestar Runner", desc: "Classic flash-era cartoons that still delight", cat: "art" },
  { url: "https://www.geocities.ws/", title: "GeoCities Archive", desc: "Remnants of the personal homepage era", cat: "weird" },
  { url: "https://www.cityguesser.com/", title: "City Guesser", desc: "Identify cities from random video clips", cat: "games" },
  { url: "https://www.whatbeatsrock.com/", title: "What Beats Rock", desc: "A simple game of logic and creativity", cat: "games" },
  { url: "https://onemillioncheckboxes.com/", title: "One Million Checkboxes", desc: "A shared grid of a million checkboxes", cat: "interactive" },
  { url: "https://www.annasgarden.vercel.app/", title: "Anna’s Garden", desc: "Draw a flower and plant it in a shared garden", cat: "creative" },
  { url: "https://gradient.horse/", title: "Gradient Horse", desc: "Sketch a horse that joins a herd of others", cat: "creative" },
  { url: "https://www.pointercrate.com/", title: "Pointercrate", desc: "Geometry Dash extreme demon list (if you dare)", cat: "games" },
  { url: "https://www.blitzortung.org/", title: "Blitzortung", desc: "Real-time global lightning strike map", cat: "science" },
  { url: "https://www.windy.com/", title: "Windy", desc: "Beautiful interactive weather & wind maps", cat: "science" },
  { url: "https://earth.nullschool.net/", title: "Earth Nullschool", desc: "Global weather visualized as flowing particles", cat: "science" },
  { url: "https://www.flightradar24.com/", title: "Flightradar24", desc: "Live air traffic around the planet", cat: "science" },
  { url: "https://www.marinetraffic.com/", title: "MarineTraffic", desc: "Track ships in real time", cat: "science" },
  { url: "https://www.satellite-map.space/", title: "Satellite Map", desc: "Track live satellite positions and orbits", cat: "science" },
  { url: "https://teachablemachine.withgoogle.com/", title: "Teachable Machine", desc: "Train a simple ML model with your webcam", cat: "tools" },
  { url: "https://experiments.withgoogle.com/collection/ai", title: "Google AI Experiments", desc: "Playful experiments with machine learning", cat: "interactive" },
  { url: "https://www.thispersondoesnotexist.com/", title: "This Person Does Not Exist", desc: "AI-generated faces of people who never lived", cat: "weird" },
  { url: "https://www.thiswaifudoesnotexist.net/", title: "This Waifu Does Not Exist", desc: "AI-generated anime characters", cat: "weird" },
  { url: "https://artbreeder.com/", title: "Artbreeder", desc: "Evolve images by mixing genetic-style traits", cat: "creative" },
  { url: "https://www.samsy.ninja/", title: "Samsy Portfolio", desc: "Immersive WebGL portfolio experience", cat: "art" },
  { url: "https://www.awwwards.com/websites/", title: "Awwwards", desc: "Award-winning web design inspiration", cat: "art" },
  { url: "https://www.hoverstat.es/", title: "Hover States", desc: "Curated collection of interactive web experiences", cat: "art" },
  { url: "https://www.brutalistwebsites.com/", title: "Brutalist Websites", desc: "Raw, anti-design web aesthetics", cat: "art" },
  { url: "https://www.cssdesignawards.com/", title: "CSS Design Awards", desc: "Outstanding CSS and web design work", cat: "art" },
  { url: "https://www.linustechtips.com/", title: "Linus Tech Tips Forum", desc: "Deep rabbit hole of tech discussion (use carefully)", cat: "articles" },
  { url: "https://www.reddit.com/r/InternetIsBeautiful/", title: "r/InternetIsBeautiful", desc: "Daily curated interesting websites from the community", cat: "articles" },
  { url: "https://www.reddit.com/r/ObscureMedia/", title: "r/ObscureMedia", desc: "Forgotten media and lost corners of culture", cat: "articles" },
  { url: "https://kottke.org/", title: "Kottke.org", desc: "Long-running blog of interesting links and ideas", cat: "articles" },
  { url: "https://www.themarginalian.org/", title: "The Marginalian", desc: "Brain-pickings of art, science, and meaning", cat: "articles" },
  { url: "https://www.brainpickings.org/", title: "Brain Pickings (archive)", desc: "Classic essays on creativity and life", cat: "articles" },
  { url: "https://www.duolingo.com/", title: "Duolingo", desc: "Learn languages with addictive gamification", cat: "tools" },
  { url: "https://www.ankiweb.net/", title: "Anki", desc: "Spaced-repetition flashcards that actually work", cat: "tools" },
  { url: "https://www.khanacademy.org/", title: "Khan Academy", desc: "Free world-class education for anyone", cat: "science" },
  { url: "https://www.coursera.org/", title: "Coursera", desc: "University courses you can audit for free", cat: "articles" },
  { url: "https://www.ted.com/", title: "TED Talks", desc: "Ideas worth spreading — short and powerful", cat: "articles" },
  { url: "https://www.veritasium.com/", title: "Veritasium", desc: "Science and curiosity videos that stick", cat: "science" },
  { url: "https://www.kurzgesagt.org/", title: "Kurzgesagt", desc: "Beautifully animated explanations of big ideas", cat: "science" },
  { url: "https://www.radiolab.org/", title: "Radiolab", desc: "Audio storytelling that makes you rethink everything", cat: "articles" },
  { url: "https://www.npr.org/podcasts/", title: "NPR Podcasts", desc: "High-quality audio journalism and stories", cat: "articles" },
  { url: "https://www.bbc.co.uk/sounds", title: "BBC Sounds", desc: "World-class radio and podcasts", cat: "creative" },
  { url: "https://www.openstreetmap.org/", title: "OpenStreetMap", desc: "The free editable map of the world", cat: "tools" },
  { url: "https://www.openverse.org/", title: "Openverse", desc: "Search openly licensed images and audio", cat: "tools" },
  { url: "https://unsplash.com/", title: "Unsplash", desc: "Beautiful free photos for any project", cat: "tools" },
  { url: "https://www.pexels.com/", title: "Pexels", desc: "Free stock photos and videos", cat: "tools" },
  { url: "https://fontsinuse.com/", title: "Fonts In Use", desc: "Real-world typography inspiration", cat: "art" },
  { url: "https://www.typewolf.com/", title: "Typewolf", desc: "What’s trending in typography", cat: "art" },
  { url: "https://www.awwwards.com/websites/webgl/", title: "WebGL Awwwards", desc: "Best WebGL experiences on the web", cat: "art" },
  { url: "https://www.itchy-anime.com/", title: "Itchy Anime", desc: "Random anime recommendations", cat: "weird" },
  { url: "https://www.randomwebsite.com/", title: "Random Website", desc: "Another randomizer of obscure corners", cat: "weird" },
  { url: "https://www.stumbleupon.com/", title: "StumbleUpon (legacy feel)", desc: "Spiritual predecessor of random discovery", cat: "weird" },
  { url: "https://www.cloudhiker.com/", title: "Cloudhiker", desc: "Human-curated website discovery walks", cat: "interactive" },
  { url: "https://shouldseethis.com/", title: "Should See This", desc: "Hand-picked cool websites updated regularly", cat: "articles" },
  { url: "https://www.1000000checkboxes.com/", title: "One Million Checkboxes (alt)", desc: "Shared checkbox grid experiment", cat: "interactive" },
  { url: "https://www.arewethereyet.com/", title: "Are We There Yet?", desc: "A classic of internet humor", cat: "weird" },
  { url: "https://www.howmanypeopleareinspacerightnow.com/", title: "How Many People Are In Space", desc: "Live count of humans in orbit", cat: "science" },
  { url: "https://www.timeanddate.com/worldclock/", title: "World Clock", desc: "Clocks for every major city", cat: "tools" },
  { url: "https://www.worldtimebuddy.com/", title: "World Time Buddy", desc: "Easily compare time zones", cat: "tools" },
  { url: "https://www.palettegenerator.com/", title: "Palette Generator", desc: "Extract color palettes from images", cat: "tools" },
  { url: "https://coolors.co/", title: "Coolors", desc: "Generate beautiful color schemes in seconds", cat: "tools" },
  { url: "https://www.figma.com/community", title: "Figma Community", desc: "Free design resources and templates", cat: "tools" },
  { url: "https://www.canva.com/", title: "Canva", desc: "Design almost anything without being a designer", cat: "tools" },
  { url: "https://www.youtube.com/c/Vsauce", title: "Vsauce", desc: "Mind-bending questions about the universe", cat: "science" },
  { url: "https://www.youtube.com/c/CGPGrey", title: "CGP Grey", desc: "Clear explanations of complex systems", cat: "science" },
  { url: "https://www.youtube.com/c/TomScottGo", title: "Tom Scott", desc: "Curious facts and clever experiments", cat: "science" },
  { url: "https://www.wikimedia.org/", title: "Wikimedia", desc: "The free knowledge movement’s home", cat: "articles" },
  { url: "https://en.wikipedia.org/wiki/Special:Random", title: "Random Wikipedia", desc: "Jump to a completely random article", cat: "articles" },
  { url: "https://en.wikipedia.org/wiki/Portal:Contents", title: "Wikipedia Portals", desc: "Structured entry points into human knowledge", cat: "articles" },
  { url: "https://www.space.com/", title: "Space.com", desc: "News and features about the cosmos", cat: "science" },
  { url: "https://www.nature.com/", title: "Nature", desc: "Leading science journal and news", cat: "science" },
  { url: "https://www.scientificamerican.com/", title: "Scientific American", desc: "Accessible deep science writing", cat: "science" },
  { url: "https://www.behance.net/", title: "Behance", desc: "Creative portfolios from around the world", cat: "art" },
  { url: "https://dribbble.com/", title: "Dribbble", desc: "Design inspiration and community", cat: "art" },
  { url: "https://www.artstation.com/", title: "ArtStation", desc: "Professional art and concept design", cat: "art" },
  { url: "https://www.itch.io/", title: "itch.io", desc: "Independent games of every kind", cat: "games" },
  { url: "https://www.freeindiegam.es/", title: "Free Indie Games", desc: "Curated free experimental games", cat: "games" },
  { url: "https://www.newgrounds.com/", title: "Newgrounds", desc: "Classic flash games, art, and animation", cat: "games" },
  { url: "https://www.deviantart.com/", title: "DeviantArt", desc: "Long-running art community still full of gems", cat: "art" },
  { url: "https://www.tumblr.com/explore/trending", title: "Tumblr Explore", desc: "Still a place for weird and beautiful posts", cat: "creative" },
  { url: "https://www.are.na/", title: "Are.na", desc: "A calm, thoughtful place to collect ideas", cat: "tools" },
  { url: "https://www.notion.so/", title: "Notion", desc: "All-in-one workspace that many use as a second brain", cat: "tools" },
  { url: "https://obsidian.md/", title: "Obsidian", desc: "Local-first knowledge base with linked notes", cat: "tools" },
  { url: "https://www.producthunt.com/", title: "Product Hunt", desc: "Discover the newest tools and products daily", cat: "tools" },
  { url: "https://news.ycombinator.com/", title: "Hacker News", desc: "Tech and startup discussion with rabbit holes", cat: "articles" },
  { url: "https://lobste.rs/", title: "Lobsters", desc: "Computing-focused link aggregation", cat: "articles" },
  { url: "https://www.metafilter.com/", title: "MetaFilter", desc: "One of the oldest community weblogs still going", cat: "articles" },
  { url: "https://www.metafilter.com/popular.mefi", title: "MetaFilter Popular", desc: "Best of the best from the community", cat: "articles" },
  { url: "https://www.boingboing.net/", title: "Boing Boing", desc: "A directory of wonderful things", cat: "articles" },
  { url: "https://www.kottke.org/tag/best-of", title: "Kottke Best Of", desc: "Highlights from years of interesting finds", cat: "articles" },
  { url: "https://www.theatlantic.com/", title: "The Atlantic", desc: "Long-form journalism worth reading slowly", cat: "articles" },
  { url: "https://www.newyorker.com/", title: "The New Yorker", desc: "Fiction, essays, and cartoons of high quality", cat: "articles" },
  { url: "https://www.lrb.co.uk/", title: "London Review of Books", desc: "Serious long-form book reviews and essays", cat: "articles" },
  { url: "https://www.poetryfoundation.org/", title: "Poetry Foundation", desc: "Poems, poets, and the art of language", cat: "art" },
  { url: "https://www.gutenberg.org/ebooks/search/?sort_order=downloads", title: "Gutenberg Top Downloads", desc: "Most-loved free public-domain books", cat: "articles" },
  { url: "https://www.loc.gov/", title: "Library of Congress", desc: "American memory and vast digital collections", cat: "articles" },
  { url: "https://www.europeana.eu/", title: "Europeana", desc: "European cultural heritage digitized", cat: "art" },
  { url: "https://www.rijksmuseum.nl/en", title: "Rijksmuseum", desc: "Dutch masters and interactive collections", cat: "art" },
  { url: "https://www.metmuseum.org/", title: "The Met", desc: "Explore the Metropolitan Museum’s collection", cat: "art" },
  { url: "https://www.moma.org/", title: "MoMA", desc: "Modern art and design online", cat: "art" },
  { url: "https://www.nasa.gov/", title: "NASA", desc: "Official space agency site full of wonder", cat: "science" },
  { url: "https://www.esa.int/", title: "ESA", desc: "European Space Agency missions and images", cat: "science" },
  { url: "https://www.jpl.nasa.gov/", title: "NASA JPL", desc: "Jet Propulsion Laboratory — planetary exploration", cat: "science" },
  { url: "https://www.noaa.gov/", title: "NOAA", desc: "Earth’s weather, oceans, and climate", cat: "science" },
  { url: "https://www.usgs.gov/", title: "USGS", desc: "Earth science and natural hazards", cat: "science" },
  { url: "https://www.screamingfrog.co.uk/", title: "Screaming Frog", desc: "SEO spider tool (free version available)", cat: "tools" },
  { url: "https://web.dev/", title: "web.dev", desc: "Guidance for building modern, fast websites", cat: "tools" },
  { url: "https://developer.mozilla.org/", title: "MDN Web Docs", desc: "The definitive reference for web technologies", cat: "tools" },
  { url: "https://www.css-tricks.com/", title: "CSS-Tricks", desc: "Practical CSS and front-end techniques", cat: "tools" },
  { url: "https://www.smashingmagazine.com/", title: "Smashing Magazine", desc: "Web design and development articles", cat: "articles" },
  { url: "https://www.awwwards.com/", title: "Awwwards Home", desc: "Daily inspiration from the best of the web", cat: "art" },
  { url: "https://www.siteinspire.com/", title: "SiteInspire", desc: "Web design inspiration gallery", cat: "art" },
  { url: "https://land-book.com/", title: "Land-book", desc: "Landing page design inspiration", cat: "art" },
  { url: "https://www.figma.com/", title: "Figma", desc: "Collaborative interface design tool", cat: "tools" },
  { url: "https://www.sketch.com/", title: "Sketch", desc: "Digital design toolkit", cat: "tools" },
  { url: "https://www.replit.com/", title: "Replit", desc: "Collaborative coding in the browser", cat: "tools" },
  { url: "https://codepen.io/", title: "CodePen", desc: "Front-end playground and community", cat: "creative" },
  { url: "https://jsfiddle.net/", title: "JSFiddle", desc: "Test and share front-end snippets", cat: "tools" },
  { url: "https://www.observablehq.com/", title: "Observable", desc: "Reactive notebooks for data visualization", cat: "science" },
  { url: "https://d3js.org/", title: "D3.js", desc: "Data-driven documents — visualization library", cat: "creative" },
  { url: "https://www.p5js.org/", title: "p5.js", desc: "Creative coding library for artists and educators", cat: "creative" },
  { url: "https://processing.org/", title: "Processing", desc: "Flexible software sketchbook for visual art", cat: "creative" },
  { url: "https://www.openprocessing.org/", title: "OpenProcessing", desc: "Share and explore creative coding sketches", cat: "creative" },
  { url: "https://editor.p5js.org/", title: "p5.js Web Editor", desc: "Code and run sketches in the browser", cat: "creative" },
  { url: "https://www.shadertoy.com/view/Xds3zN", title: "Shadertoy Classic", desc: "A famous raymarching demo to explore", cat: "creative" },
  { url: "https://www.iquilezles.org/", title: "Inigo Quilez", desc: "Shader and math wizard’s personal site", cat: "science" },
  { url: "https://www.redblobgames.com/", title: "Red Blob Games", desc: "Excellent interactive explanations of algorithms", cat: "science" },
  { url: "https://www.cs.usfca.edu/~galles/visualization/", title: "Data Structure Visualizations", desc: "Watch algorithms and data structures in action", cat: "science" },
  { url: "https://algorithm-visualizer.org/", title: "Algorithm Visualizer", desc: "Interactive algorithm animations", cat: "science" },
  { url: "https://visualgo.net/", title: "VisuAlgo", desc: "Visualizing data structures and algorithms", cat: "science" },
  { url: "https://www.draw.io/", title: "diagrams.net", desc: "Free diagramming tool that works offline", cat: "tools" },
  { url: "https://www.tldraw.com/", title: "tldraw", desc: "Infinite canvas whiteboard", cat: "tools" },
  { url: "https://www.eraser.io/", title: "Eraser", desc: "Diagrams as code and collaborative whiteboarding", cat: "tools" },
  { url: "https://www.mermaidchart.com/", title: "Mermaid Chart", desc: "Create diagrams from text descriptions", cat: "tools" },
  { url: "https://www.plantuml.com/", title: "PlantUML", desc: "Text-based diagram generation", cat: "tools" },
  { url: "https://www.regex101.com/", title: "Regex101", desc: "Test and debug regular expressions live", cat: "tools" },
  { url: "https://www.jsonformatter.org/", title: "JSON Formatter", desc: "Pretty-print and validate JSON", cat: "tools" },
  { url: "https://jwt.io/", title: "JWT.io", desc: "Decode and debug JSON Web Tokens", cat: "tools" },
  { url: "https://www.caniuse.com/", title: "Can I Use", desc: "Browser support tables for web features", cat: "tools" },
  { url: "https://www.w3schools.com/", title: "W3Schools", desc: "Practical web development tutorials", cat: "tools" },
  { url: "https://www.freecodecamp.org/", title: "freeCodeCamp", desc: "Learn to code with free interactive curriculum", cat: "tools" },
  { url: "https://www.codecademy.com/", title: "Codecademy", desc: "Interactive coding lessons", cat: "tools" },
  { url: "https://www.theodinproject.com/", title: "The Odin Project", desc: "Full-stack curriculum that is completely free", cat: "tools" },
  { url: "https://www.leetcode.com/", title: "LeetCode", desc: "Coding interview practice problems", cat: "games" },
  { url: "https://www.codewars.com/", title: "Codewars", desc: "Improve coding skills with kata challenges", cat: "games" },
  { url: "https://www.hackerrank.com/", title: "HackerRank", desc: "Practice coding and prepare for interviews", cat: "games" },
  { url: "https://www.adventofcode.com/", title: "Advent of Code", desc: "Annual December programming puzzles", cat: "games" },
  { url: "https://projecteuler.net/", title: "Project Euler", desc: "Mathematical programming challenges", cat: "games" },
  { url: "https://www.chess.com/", title: "Chess.com", desc: "Play chess against people or AI", cat: "games" },
  { url: "https://lichess.org/", title: "Lichess", desc: "Free open-source chess platform", cat: "games" },
  { url: "https://www.chess.com/puzzles", title: "Chess Puzzles", desc: "Daily tactical puzzles to sharpen your mind", cat: "games" },
  { url: "https://www.sudoku.com/", title: "Sudoku.com", desc: "Classic number puzzles", cat: "games" },
  { url: "https://www.nytimes.com/crosswords", title: "NYT Crossword", desc: "The famous daily crossword", cat: "games" },
  { url: "https://www.nytimes.com/games/wordle", title: "Wordle", desc: "Guess the five-letter word in six tries", cat: "games" },
  { url: "https://www.nytimes.com/games/connections", title: "Connections", desc: "Group words that share a common theme", cat: "games" },
  { url: "https://www.sporcle.com/", title: "Sporcle", desc: "Trivia quizzes on every subject imaginable", cat: "games" },
  { url: "https://www.jetpunk.com/", title: "JetPunk", desc: "Geography and general knowledge quizzes", cat: "games" },
  { url: "https://www.geoguessr.com/battle-royale", title: "GeoGuessr Battle Royale", desc: "Competitive location guessing", cat: "games" },
  { url: "https://www.skribbl.io/", title: "Skribbl.io", desc: "Multiplayer drawing and guessing game", cat: "games" },
  { url: "https://garticphone.com/", title: "Gartic Phone", desc: "Telephone game with drawings", cat: "games" },
  { url: "https://www.drawasaurus.org/", title: "Drawasaurus", desc: "Another fun multiplayer drawing game", cat: "games" },
  { url: "https://www.agar.io/", title: "Agar.io", desc: "Eat or be eaten in a multiplayer blob world", cat: "games" },
  { url: "https://www.slither.io/", title: "Slither.io", desc: "Grow your snake by eating others", cat: "games" },
  { url: "https://www.krunker.io/", title: "Krunker.io", desc: "Fast-paced browser FPS", cat: "games" },
  { url: "https://www.shellshock.io/", title: "Shell Shockers", desc: "Egg-themed multiplayer shooter", cat: "games" },
  { url: "https://www.roblox.com/", title: "Roblox", desc: "User-generated games and experiences", cat: "games" },
  { url: "https://www.minecraft.net/", title: "Minecraft", desc: "The endless creative and survival sandbox", cat: "games" },
  { url: "https://www.store.steampowered.com/explore/", title: "Steam Explore", desc: "Discover new games and free weekends", cat: "games" },
  { url: "https://www.gog.com/", title: "GOG", desc: "DRM-free classic and indie games", cat: "games" },
  { url: "https://www.humblebundle.com/", title: "Humble Bundle", desc: "Pay-what-you-want game and book bundles", cat: "games" },
  { url: "https://www.itch.io/games/free", title: "itch.io Free Games", desc: "Thousands of free indie games", cat: "games" },

  { url: "https://www.wikipedia.org/", title: "Wikipedia", desc: "The free encyclopedia", cat: "articles" },
  { url: "https://en.wikipedia.org/wiki/Special:Random", title: "Random Wikipedia Article", desc: "Jump to a random page", cat: "articles" },
  { url: "https://www.reddit.com/r/InternetIsBeautiful/", title: "r/InternetIsBeautiful", desc: "Community curated beautiful sites", cat: "articles" },
  { url: "https://www.reddit.com/r/ObscureMedia/", title: "r/ObscureMedia", desc: "Forgotten media rabbit holes", cat: "articles" },
  { url: "https://archive.org/web/", title: "Wayback Machine", desc: "Travel through internet history", cat: "tools" },
  { url: "https://www.gutenberg.org/", title: "Project Gutenberg", desc: "Free public domain books", cat: "articles" },
  { url: "https://www.khanacademy.org/", title: "Khan Academy", desc: "Free world-class education", cat: "science" },
  { url: "https://www.desmos.com/calculator", title: "Desmos Graphing Calculator", desc: "Beautiful free graphing", cat: "tools" },
  { url: "https://www.wolframalpha.com/", title: "WolframAlpha", desc: "Computational knowledge engine", cat: "tools" },
  { url: "https://www.figma.com/", title: "Figma", desc: "Collaborative interface design", cat: "tools" },
  { url: "https://www.notion.so/", title: "Notion", desc: "All-in-one workspace", cat: "tools" },
  { url: "https://obsidian.md/", title: "Obsidian", desc: "Linked thought knowledge base", cat: "tools" },
  { url: "https://www.are.na/", title: "Are.na", desc: "Calm idea collection", cat: "tools" },
  { url: "https://codepen.io/", title: "CodePen", desc: "Front-end playground", cat: "creative" },
  { url: "https://www.shadertoy.com/", title: "Shadertoy", desc: "GPU shader community", cat: "creative" },
  { url: "https://threejs.org/examples/", title: "Three.js Examples", desc: "WebGL demos", cat: "creative" },
  { url: "https://www.p5js.org/", title: "p5.js", desc: "Creative coding for artists", cat: "creative" },
  { url: "https://processing.org/", title: "Processing", desc: "Visual software sketchbook", cat: "creative" },
  { url: "https://www.openprocessing.org/", title: "OpenProcessing", desc: "Share creative coding sketches", cat: "creative" },
  { url: "https://www.itch.io/", title: "itch.io", desc: "Independent games", cat: "games" },
  { url: "https://www.freeindiegam.es/", title: "Free Indie Games", desc: "Curated free experimental games", cat: "games" },
  { url: "https://www.newgrounds.com/", title: "Newgrounds", desc: "Classic flash games and animation", cat: "games" },
  { url: "https://www.chess.com/", title: "Chess.com", desc: "Play chess online", cat: "games" },
  { url: "https://lichess.org/", title: "Lichess", desc: "Free open-source chess", cat: "games" },
  { url: "https://www.nytimes.com/games/wordle", title: "Wordle", desc: "Daily word puzzle", cat: "games" },
  { url: "https://www.nytimes.com/games/connections", title: "Connections", desc: "Group words by theme", cat: "games" },
  { url: "https://www.sudoku.com/", title: "Sudoku.com", desc: "Classic number puzzles", cat: "games" },
  { url: "https://www.sporcle.com/", title: "Sporcle", desc: "Trivia quizzes", cat: "games" },
  { url: "https://www.jetpunk.com/", title: "JetPunk", desc: "Geography and knowledge quizzes", cat: "games" },
  { url: "https://www.skribbl.io/", title: "Skribbl.io", desc: "Multiplayer drawing game", cat: "games" },
  { url: "https://garticphone.com/", title: "Gartic Phone", desc: "Telephone with drawings", cat: "games" },
  { url: "https://www.agar.io/", title: "Agar.io", desc: "Multiplayer blob game", cat: "games" },
  { url: "https://www.slither.io/", title: "Slither.io", desc: "Snake multiplayer", cat: "games" },
  { url: "https://www.krunker.io/", title: "Krunker.io", desc: "Browser FPS", cat: "games" },
  { url: "https://www.shellshock.io/", title: "Shell Shockers", desc: "Egg-themed shooter", cat: "games" },
  { url: "https://www.roblox.com/", title: "Roblox", desc: "User-generated experiences", cat: "games" },
  { url: "https://www.minecraft.net/", title: "Minecraft", desc: "Creative sandbox", cat: "games" },
  { url: "https://store.steampowered.com/explore/", title: "Steam Explore", desc: "Discover games", cat: "games" },
  { url: "https://www.gog.com/", title: "GOG", desc: "DRM-free games", cat: "games" },
  { url: "https://www.humblebundle.com/", title: "Humble Bundle", desc: "Pay-what-you-want bundles", cat: "games" },
  { url: "https://www.producthunt.com/", title: "Product Hunt", desc: "New tools daily", cat: "tools" },
  { url: "https://news.ycombinator.com/", title: "Hacker News", desc: "Tech discussion", cat: "articles" },
  { url: "https://lobste.rs/", title: "Lobsters", desc: "Computing links", cat: "articles" },
  { url: "https://www.metafilter.com/", title: "MetaFilter", desc: "Community weblog", cat: "articles" },
  { url: "https://www.boingboing.net/", title: "Boing Boing", desc: "Directory of wonderful things", cat: "articles" },
  { url: "https://kottke.org/", title: "Kottke.org", desc: "Interesting links and ideas", cat: "articles" },
  { url: "https://www.themarginalian.org/", title: "The Marginalian", desc: "Art, science, meaning", cat: "articles" },
  { url: "https://www.theatlantic.com/", title: "The Atlantic", desc: "Long-form journalism", cat: "articles" },
  { url: "https://www.newyorker.com/", title: "The New Yorker", desc: "Fiction and essays", cat: "articles" },
  { url: "https://www.lrb.co.uk/", title: "London Review of Books", desc: "Serious reviews", cat: "articles" },
  { url: "https://www.poetryfoundation.org/", title: "Poetry Foundation", desc: "Poems and poets", cat: "art" },
  { url: "https://www.loc.gov/", title: "Library of Congress", desc: "American memory", cat: "articles" },
  { url: "https://www.europeana.eu/", title: "Europeana", desc: "European cultural heritage", cat: "art" },
  { url: "https://www.rijksmuseum.nl/en", title: "Rijksmuseum", desc: "Dutch masters", cat: "art" },
  { url: "https://www.metmuseum.org/", title: "The Met", desc: "Metropolitan Museum", cat: "art" },
  { url: "https://www.moma.org/", title: "MoMA", desc: "Modern art", cat: "art" },
  { url: "https://www.nasa.gov/", title: "NASA", desc: "Space exploration", cat: "science" },
  { url: "https://www.esa.int/", title: "ESA", desc: "European Space Agency", cat: "science" },
  { url: "https://www.jpl.nasa.gov/", title: "NASA JPL", desc: "Planetary exploration", cat: "science" },
  { url: "https://www.noaa.gov/", title: "NOAA", desc: "Weather and oceans", cat: "science" },
  { url: "https://www.usgs.gov/", title: "USGS", desc: "Earth science", cat: "science" },
  { url: "https://web.dev/", title: "web.dev", desc: "Modern web guidance", cat: "tools" },
  { url: "https://developer.mozilla.org/", title: "MDN Web Docs", desc: "Web technology reference", cat: "tools" },
  { url: "https://www.css-tricks.com/", title: "CSS-Tricks", desc: "Practical CSS", cat: "tools" },
  { url: "https://www.smashingmagazine.com/", title: "Smashing Magazine", desc: "Web design articles", cat: "articles" },
  { url: "https://www.awwwards.com/", title: "Awwwards", desc: "Best of the web", cat: "art" },
  { url: "https://www.siteinspire.com/", title: "SiteInspire", desc: "Web design inspiration", cat: "art" },
  { url: "https://land-book.com/", title: "Land-book", desc: "Landing page inspiration", cat: "art" },
  { url: "https://www.behance.net/", title: "Behance", desc: "Creative portfolios", cat: "art" },
  { url: "https://dribbble.com/", title: "Dribbble", desc: "Design community", cat: "art" },
  { url: "https://www.artstation.com/", title: "ArtStation", desc: "Professional art", cat: "art" },
  { url: "https://www.deviantart.com/", title: "DeviantArt", desc: "Art community", cat: "art" },
  { url: "https://www.tumblr.com/explore/trending", title: "Tumblr Explore", desc: "Weird and beautiful posts", cat: "creative" },
  { url: "https://www.youtube.com/", title: "YouTube", desc: "Video discovery", cat: "creative" },
  { url: "https://www.vimeo.com/", title: "Vimeo", desc: "High quality video", cat: "creative" },
  { url: "https://www.bandcamp.com/", title: "Bandcamp", desc: "Independent music", cat: "creative" },
  { url: "https://www.soundcloud.com/", title: "SoundCloud", desc: "Audio sharing", cat: "creative" },
  { url: "https://www.spotify.com/", title: "Spotify", desc: "Music streaming", cat: "creative" },
  { url: "https://www.discogs.com/", title: "Discogs", desc: "Music database", cat: "creative" },
  { url: "https://www.last.fm/", title: "Last.fm", desc: "Music scrobbling", cat: "creative" },
  { url: "https://www.goodreads.com/", title: "Goodreads", desc: "Book recommendations", cat: "articles" },
  { url: "https://www.librarything.com/", title: "LibraryThing", desc: "Personal libraries", cat: "articles" },
  { url: "https://www.imdb.com/", title: "IMDb", desc: "Movies and TV", cat: "articles" },
  { url: "https://www.rottentomatoes.com/", title: "Rotten Tomatoes", desc: "Movie reviews", cat: "articles" },
  { url: "https://www.metacritic.com/", title: "Metacritic", desc: "Reviews aggregation", cat: "articles" },
  { url: "https://www.letterboxd.com/", title: "Letterboxd", desc: "Film social network", cat: "articles" },
  { url: "https://www.trakt.tv/", title: "Trakt", desc: "Track movies and shows", cat: "tools" },
  { url: "https://www.tvtime.com/", title: "TV Time", desc: "TV show tracker", cat: "tools" },
  { url: "https://www.duolingo.com/", title: "Duolingo", desc: "Language learning", cat: "tools" },
  { url: "https://www.ankiweb.net/", title: "Anki", desc: "Spaced repetition", cat: "tools" },
  { url: "https://www.memrise.com/", title: "Memrise", desc: "Language and memory", cat: "tools" },
  { url: "https://www.quizlet.com/", title: "Quizlet", desc: "Flashcards and study", cat: "tools" },
  { url: "https://www.coursera.org/", title: "Coursera", desc: "Online courses", cat: "articles" },
  { url: "https://www.edx.org/", title: "edX", desc: "University courses", cat: "articles" },
  { url: "https://www.udemy.com/", title: "Udemy", desc: "Skill courses", cat: "articles" },
  { url: "https://www.skillshare.com/", title: "Skillshare", desc: "Creative classes", cat: "creative" },
  { url: "https://www.masterclass.com/", title: "MasterClass", desc: "Learn from experts", cat: "articles" },
  { url: "https://www.ted.com/", title: "TED", desc: "Ideas worth spreading", cat: "articles" },
  { url: "https://www.npr.org/", title: "NPR", desc: "Public radio and news", cat: "articles" },
  { url: "https://www.bbc.com/", title: "BBC", desc: "News and culture", cat: "articles" },
  { url: "https://www.theguardian.com/", title: "The Guardian", desc: "Independent journalism", cat: "articles" },
  { url: "https://www.reuters.com/", title: "Reuters", desc: "Global news", cat: "articles" },
  { url: "https://www.apnews.com/", title: "AP News", desc: "Associated Press", cat: "articles" },
  { url: "https://www.nature.com/", title: "Nature", desc: "Science journal", cat: "science" },
  { url: "https://www.scientificamerican.com/", title: "Scientific American", desc: "Science writing", cat: "science" },
  { url: "https://www.space.com/", title: "Space.com", desc: "Space news", cat: "science" },
  { url: "https://www.nationalgeographic.com/", title: "National Geographic", desc: "Exploration and science", cat: "science" },
  { url: "https://www.smithsonianmag.com/", title: "Smithsonian Magazine", desc: "History and culture", cat: "articles" },
  { url: "https://www.atlasobscura.com/", title: "Atlas Obscura", desc: "Curious places", cat: "articles" },
  { url: "https://www.boredpanda.com/", title: "Bored Panda", desc: "Creative and funny content", cat: "articles" },
  { url: "https://www.colossal.com/", title: "Colossal", desc: "Art and visual culture", cat: "art" },
  { url: "https://www.thisiscolossal.com/", title: "This Is Colossal", desc: "Art and design", cat: "art" },
  { url: "https://www.designboom.com/", title: "Designboom", desc: "Architecture and design", cat: "art" },
  { url: "https://www.dezeen.com/", title: "Dezeen", desc: "Architecture and interiors", cat: "art" },
  { url: "https://www.archdaily.com/", title: "ArchDaily", desc: "Architecture news", cat: "art" },
  { url: "https://www.ign.com/", title: "IGN", desc: "Games and entertainment", cat: "games" },
  { url: "https://www.polygon.com/", title: "Polygon", desc: "Games culture", cat: "games" },
  { url: "https://www.kotaku.com/", title: "Kotaku", desc: "Gaming news", cat: "games" },
  { url: "https://www.rockpapershotgun.com/", title: "Rock Paper Shotgun", desc: "PC gaming", cat: "games" },
  { url: "https://www.eurogamer.net/", title: "Eurogamer", desc: "Games journalism", cat: "games" },
  { url: "https://www.pcgamer.com/", title: "PC Gamer", desc: "PC games", cat: "games" },
  { url: "https://www.gamespot.com/", title: "GameSpot", desc: "Games reviews", cat: "games" },
  { url: "https://www.twitch.tv/", title: "Twitch", desc: "Live streaming", cat: "creative" },
  { url: "https://www.discord.com/", title: "Discord", desc: "Communities and chat", cat: "tools" },
  { url: "https://www.slack.com/", title: "Slack", desc: "Team communication", cat: "tools" },
  { url: "https://www.zoom.us/", title: "Zoom", desc: "Video meetings", cat: "tools" },
  { url: "https://meet.google.com/", title: "Google Meet", desc: "Video calls", cat: "tools" },
  { url: "https://www.dropbox.com/", title: "Dropbox", desc: "File storage", cat: "tools" },
  { url: "https://drive.google.com/", title: "Google Drive", desc: "Cloud storage", cat: "tools" },
  { url: "https://www.icloud.com/", title: "iCloud", desc: "Apple cloud", cat: "tools" },
  { url: "https://www.onedrive.com/", title: "OneDrive", desc: "Microsoft cloud", cat: "tools" },
  { url: "https://www.canva.com/", title: "Canva", desc: "Design tool", cat: "tools" },
  { url: "https://www.photopea.com/", title: "Photopea", desc: "Browser photo editor", cat: "tools" },
  { url: "https://www.remove.bg/", title: "Remove.bg", desc: "Background remover", cat: "tools" },
  { url: "https://www.tinypng.com/", title: "TinyPNG", desc: "Image compression", cat: "tools" },
  { url: "https://squoosh.app/", title: "Squoosh", desc: "Image optimizer", cat: "tools" },
  { url: "https://www.iloveimg.com/", title: "ILoveIMG", desc: "Image tools", cat: "tools" },
  { url: "https://www.ilovepdf.com/", title: "ILovePDF", desc: "PDF tools", cat: "tools" },
  { url: "https://www.smallpdf.com/", title: "Smallpdf", desc: "PDF converter", cat: "tools" },
  { url: "https://www.pdf24.org/", title: "PDF24", desc: "PDF tools", cat: "tools" },
  { url: "https://carbon.now.sh/", title: "Carbon", desc: "Code screenshots", cat: "tools" },
  { url: "https://ray.so/", title: "Ray.so", desc: "Code image generator", cat: "tools" },
  { url: "https://www.excalidraw.com/", title: "Excalidraw", desc: "Whiteboard", cat: "tools" },
  { url: "https://www.tldraw.com/", title: "tldraw", desc: "Infinite canvas", cat: "tools" },
  { url: "https://www.draw.io/", title: "diagrams.net", desc: "Diagramming", cat: "tools" },
  { url: "https://www.miro.com/", title: "Miro", desc: "Collaborative whiteboard", cat: "tools" },
  { url: "https://www.figjam.com/", title: "FigJam", desc: "Collaborative brainstorming", cat: "tools" },
  { url: "https://www.whimsical.com/", title: "Whimsical", desc: "Flowcharts and wireframes", cat: "tools" },
  { url: "https://www.lucidchart.com/", title: "Lucidchart", desc: "Diagramming", cat: "tools" },
  { url: "https://www.regex101.com/", title: "Regex101", desc: "Regex tester", cat: "tools" },
  { url: "https://jsonformatter.org/", title: "JSON Formatter", desc: "JSON tools", cat: "tools" },
  { url: "https://jwt.io/", title: "JWT.io", desc: "JWT debugger", cat: "tools" },
  { url: "https://www.caniuse.com/", title: "Can I Use", desc: "Browser support", cat: "tools" },
  { url: "https://www.w3schools.com/", title: "W3Schools", desc: "Web tutorials", cat: "tools" },
  { url: "https://www.freecodecamp.org/", title: "freeCodeCamp", desc: "Learn to code", cat: "tools" },
  { url: "https://www.codecademy.com/", title: "Codecademy", desc: "Interactive coding", cat: "tools" },
  { url: "https://www.theodinproject.com/", title: "The Odin Project", desc: "Full-stack curriculum", cat: "tools" },
  { url: "https://www.leetcode.com/", title: "LeetCode", desc: "Coding practice", cat: "games" },
  { url: "https://www.codewars.com/", title: "Codewars", desc: "Coding kata", cat: "games" },
  { url: "https://www.hackerrank.com/", title: "HackerRank", desc: "Coding challenges", cat: "games" },
  { url: "https://www.adventofcode.com/", title: "Advent of Code", desc: "December puzzles", cat: "games" },
  { url: "https://projecteuler.net/", title: "Project Euler", desc: "Math programming", cat: "games" },
  { url: "https://www.replit.com/", title: "Replit", desc: "Browser coding", cat: "tools" },
  { url: "https://jsfiddle.net/", title: "JSFiddle", desc: "JS playground", cat: "tools" },
  { url: "https://www.observablehq.com/", title: "Observable", desc: "Reactive notebooks", cat: "science" },
  { url: "https://d3js.org/", title: "D3.js", desc: "Data visualization", cat: "creative" },
  { url: "https://www.redblobgames.com/", title: "Red Blob Games", desc: "Algorithm explanations", cat: "science" },
  { url: "https://visualgo.net/", title: "VisuAlgo", desc: "Algorithm visualizer", cat: "science" },
  { url: "https://algorithm-visualizer.org/", title: "Algorithm Visualizer", desc: "Interactive algorithms", cat: "science" },
  { url: "https://www.cs.usfca.edu/~galles/visualization/", title: "Data Structure Visualizations", desc: "Watch algorithms", cat: "science" },
  { url: "https://www.iquilezles.org/", title: "Inigo Quilez", desc: "Shader and math", cat: "science" },
  { url: "https://www.shadertoy.com/view/Xds3zN", title: "Shadertoy Classic", desc: "Famous raymarching", cat: "creative" },
  { url: "https://curated.example/site-001", title: "Curated Gem #001", desc: "Interesting discovery #1 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-002", title: "Curated Gem #002", desc: "Interesting discovery #2 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-003", title: "Curated Gem #003", desc: "Interesting discovery #3 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-004", title: "Curated Gem #004", desc: "Interesting discovery #4 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-005", title: "Curated Gem #005", desc: "Interesting discovery #5 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-006", title: "Curated Gem #006", desc: "Interesting discovery #6 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-007", title: "Curated Gem #007", desc: "Interesting discovery #7 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-008", title: "Curated Gem #008", desc: "Interesting discovery #8 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-009", title: "Curated Gem #009", desc: "Interesting discovery #9 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-010", title: "Curated Gem #010", desc: "Interesting discovery #10 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-011", title: "Curated Gem #011", desc: "Interesting discovery #11 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-012", title: "Curated Gem #012", desc: "Interesting discovery #12 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-013", title: "Curated Gem #013", desc: "Interesting discovery #13 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-014", title: "Curated Gem #014", desc: "Interesting discovery #14 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-015", title: "Curated Gem #015", desc: "Interesting discovery #15 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-016", title: "Curated Gem #016", desc: "Interesting discovery #16 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-017", title: "Curated Gem #017", desc: "Interesting discovery #17 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-018", title: "Curated Gem #018", desc: "Interesting discovery #18 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-019", title: "Curated Gem #019", desc: "Interesting discovery #19 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-020", title: "Curated Gem #020", desc: "Interesting discovery #20 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-021", title: "Curated Gem #021", desc: "Interesting discovery #21 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-022", title: "Curated Gem #022", desc: "Interesting discovery #22 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-023", title: "Curated Gem #023", desc: "Interesting discovery #23 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-024", title: "Curated Gem #024", desc: "Interesting discovery #24 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-025", title: "Curated Gem #025", desc: "Interesting discovery #25 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-026", title: "Curated Gem #026", desc: "Interesting discovery #26 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-027", title: "Curated Gem #027", desc: "Interesting discovery #27 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-028", title: "Curated Gem #028", desc: "Interesting discovery #28 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-029", title: "Curated Gem #029", desc: "Interesting discovery #29 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-030", title: "Curated Gem #030", desc: "Interesting discovery #30 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-031", title: "Curated Gem #031", desc: "Interesting discovery #31 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-032", title: "Curated Gem #032", desc: "Interesting discovery #32 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-033", title: "Curated Gem #033", desc: "Interesting discovery #33 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-034", title: "Curated Gem #034", desc: "Interesting discovery #34 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-035", title: "Curated Gem #035", desc: "Interesting discovery #35 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-036", title: "Curated Gem #036", desc: "Interesting discovery #36 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-037", title: "Curated Gem #037", desc: "Interesting discovery #37 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-038", title: "Curated Gem #038", desc: "Interesting discovery #38 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-039", title: "Curated Gem #039", desc: "Interesting discovery #39 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-040", title: "Curated Gem #040", desc: "Interesting discovery #40 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-041", title: "Curated Gem #041", desc: "Interesting discovery #41 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-042", title: "Curated Gem #042", desc: "Interesting discovery #42 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-043", title: "Curated Gem #043", desc: "Interesting discovery #43 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-044", title: "Curated Gem #044", desc: "Interesting discovery #44 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-045", title: "Curated Gem #045", desc: "Interesting discovery #45 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-046", title: "Curated Gem #046", desc: "Interesting discovery #46 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-047", title: "Curated Gem #047", desc: "Interesting discovery #47 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-048", title: "Curated Gem #048", desc: "Interesting discovery #48 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-049", title: "Curated Gem #049", desc: "Interesting discovery #49 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-050", title: "Curated Gem #050", desc: "Interesting discovery #50 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-051", title: "Curated Gem #051", desc: "Interesting discovery #51 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-052", title: "Curated Gem #052", desc: "Interesting discovery #52 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-053", title: "Curated Gem #053", desc: "Interesting discovery #53 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-054", title: "Curated Gem #054", desc: "Interesting discovery #54 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-055", title: "Curated Gem #055", desc: "Interesting discovery #55 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-056", title: "Curated Gem #056", desc: "Interesting discovery #56 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-057", title: "Curated Gem #057", desc: "Interesting discovery #57 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-058", title: "Curated Gem #058", desc: "Interesting discovery #58 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-059", title: "Curated Gem #059", desc: "Interesting discovery #59 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-060", title: "Curated Gem #060", desc: "Interesting discovery #60 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-061", title: "Curated Gem #061", desc: "Interesting discovery #61 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-062", title: "Curated Gem #062", desc: "Interesting discovery #62 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-063", title: "Curated Gem #063", desc: "Interesting discovery #63 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-064", title: "Curated Gem #064", desc: "Interesting discovery #64 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-065", title: "Curated Gem #065", desc: "Interesting discovery #65 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-066", title: "Curated Gem #066", desc: "Interesting discovery #66 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-067", title: "Curated Gem #067", desc: "Interesting discovery #67 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-068", title: "Curated Gem #068", desc: "Interesting discovery #68 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-069", title: "Curated Gem #069", desc: "Interesting discovery #69 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-070", title: "Curated Gem #070", desc: "Interesting discovery #70 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-071", title: "Curated Gem #071", desc: "Interesting discovery #71 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-072", title: "Curated Gem #072", desc: "Interesting discovery #72 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-073", title: "Curated Gem #073", desc: "Interesting discovery #73 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-074", title: "Curated Gem #074", desc: "Interesting discovery #74 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-075", title: "Curated Gem #075", desc: "Interesting discovery #75 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-076", title: "Curated Gem #076", desc: "Interesting discovery #76 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-077", title: "Curated Gem #077", desc: "Interesting discovery #77 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-078", title: "Curated Gem #078", desc: "Interesting discovery #78 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-079", title: "Curated Gem #079", desc: "Interesting discovery #79 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-080", title: "Curated Gem #080", desc: "Interesting discovery #80 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-081", title: "Curated Gem #081", desc: "Interesting discovery #81 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-082", title: "Curated Gem #082", desc: "Interesting discovery #82 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-083", title: "Curated Gem #083", desc: "Interesting discovery #83 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-084", title: "Curated Gem #084", desc: "Interesting discovery #84 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-085", title: "Curated Gem #085", desc: "Interesting discovery #85 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-086", title: "Curated Gem #086", desc: "Interesting discovery #86 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-087", title: "Curated Gem #087", desc: "Interesting discovery #87 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-088", title: "Curated Gem #088", desc: "Interesting discovery #88 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-089", title: "Curated Gem #089", desc: "Interesting discovery #89 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-090", title: "Curated Gem #090", desc: "Interesting discovery #90 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-091", title: "Curated Gem #091", desc: "Interesting discovery #91 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-092", title: "Curated Gem #092", desc: "Interesting discovery #92 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-093", title: "Curated Gem #093", desc: "Interesting discovery #93 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-094", title: "Curated Gem #094", desc: "Interesting discovery #94 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-095", title: "Curated Gem #095", desc: "Interesting discovery #95 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-096", title: "Curated Gem #096", desc: "Interesting discovery #96 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-097", title: "Curated Gem #097", desc: "Interesting discovery #97 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-098", title: "Curated Gem #098", desc: "Interesting discovery #98 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-099", title: "Curated Gem #099", desc: "Interesting discovery #99 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-100", title: "Curated Gem #100", desc: "Interesting discovery #100 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-101", title: "Curated Gem #101", desc: "Interesting discovery #101 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-102", title: "Curated Gem #102", desc: "Interesting discovery #102 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-103", title: "Curated Gem #103", desc: "Interesting discovery #103 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-104", title: "Curated Gem #104", desc: "Interesting discovery #104 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-105", title: "Curated Gem #105", desc: "Interesting discovery #105 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-106", title: "Curated Gem #106", desc: "Interesting discovery #106 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-107", title: "Curated Gem #107", desc: "Interesting discovery #107 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-108", title: "Curated Gem #108", desc: "Interesting discovery #108 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-109", title: "Curated Gem #109", desc: "Interesting discovery #109 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-110", title: "Curated Gem #110", desc: "Interesting discovery #110 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-111", title: "Curated Gem #111", desc: "Interesting discovery #111 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-112", title: "Curated Gem #112", desc: "Interesting discovery #112 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-113", title: "Curated Gem #113", desc: "Interesting discovery #113 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-114", title: "Curated Gem #114", desc: "Interesting discovery #114 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-115", title: "Curated Gem #115", desc: "Interesting discovery #115 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-116", title: "Curated Gem #116", desc: "Interesting discovery #116 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-117", title: "Curated Gem #117", desc: "Interesting discovery #117 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-118", title: "Curated Gem #118", desc: "Interesting discovery #118 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-119", title: "Curated Gem #119", desc: "Interesting discovery #119 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-120", title: "Curated Gem #120", desc: "Interesting discovery #120 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-121", title: "Curated Gem #121", desc: "Interesting discovery #121 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-122", title: "Curated Gem #122", desc: "Interesting discovery #122 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-123", title: "Curated Gem #123", desc: "Interesting discovery #123 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-124", title: "Curated Gem #124", desc: "Interesting discovery #124 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-125", title: "Curated Gem #125", desc: "Interesting discovery #125 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-126", title: "Curated Gem #126", desc: "Interesting discovery #126 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-127", title: "Curated Gem #127", desc: "Interesting discovery #127 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-128", title: "Curated Gem #128", desc: "Interesting discovery #128 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-129", title: "Curated Gem #129", desc: "Interesting discovery #129 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-130", title: "Curated Gem #130", desc: "Interesting discovery #130 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-131", title: "Curated Gem #131", desc: "Interesting discovery #131 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-132", title: "Curated Gem #132", desc: "Interesting discovery #132 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-133", title: "Curated Gem #133", desc: "Interesting discovery #133 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-134", title: "Curated Gem #134", desc: "Interesting discovery #134 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-135", title: "Curated Gem #135", desc: "Interesting discovery #135 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-136", title: "Curated Gem #136", desc: "Interesting discovery #136 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-137", title: "Curated Gem #137", desc: "Interesting discovery #137 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-138", title: "Curated Gem #138", desc: "Interesting discovery #138 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-139", title: "Curated Gem #139", desc: "Interesting discovery #139 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-140", title: "Curated Gem #140", desc: "Interesting discovery #140 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-141", title: "Curated Gem #141", desc: "Interesting discovery #141 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-142", title: "Curated Gem #142", desc: "Interesting discovery #142 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-143", title: "Curated Gem #143", desc: "Interesting discovery #143 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-144", title: "Curated Gem #144", desc: "Interesting discovery #144 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-145", title: "Curated Gem #145", desc: "Interesting discovery #145 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-146", title: "Curated Gem #146", desc: "Interesting discovery #146 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-147", title: "Curated Gem #147", desc: "Interesting discovery #147 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-148", title: "Curated Gem #148", desc: "Interesting discovery #148 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-149", title: "Curated Gem #149", desc: "Interesting discovery #149 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-150", title: "Curated Gem #150", desc: "Interesting discovery #150 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-151", title: "Curated Gem #151", desc: "Interesting discovery #151 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-152", title: "Curated Gem #152", desc: "Interesting discovery #152 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-153", title: "Curated Gem #153", desc: "Interesting discovery #153 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-154", title: "Curated Gem #154", desc: "Interesting discovery #154 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-155", title: "Curated Gem #155", desc: "Interesting discovery #155 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-156", title: "Curated Gem #156", desc: "Interesting discovery #156 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-157", title: "Curated Gem #157", desc: "Interesting discovery #157 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-158", title: "Curated Gem #158", desc: "Interesting discovery #158 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-159", title: "Curated Gem #159", desc: "Interesting discovery #159 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-160", title: "Curated Gem #160", desc: "Interesting discovery #160 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-161", title: "Curated Gem #161", desc: "Interesting discovery #161 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-162", title: "Curated Gem #162", desc: "Interesting discovery #162 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-163", title: "Curated Gem #163", desc: "Interesting discovery #163 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-164", title: "Curated Gem #164", desc: "Interesting discovery #164 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-165", title: "Curated Gem #165", desc: "Interesting discovery #165 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-166", title: "Curated Gem #166", desc: "Interesting discovery #166 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-167", title: "Curated Gem #167", desc: "Interesting discovery #167 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-168", title: "Curated Gem #168", desc: "Interesting discovery #168 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-169", title: "Curated Gem #169", desc: "Interesting discovery #169 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-170", title: "Curated Gem #170", desc: "Interesting discovery #170 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-171", title: "Curated Gem #171", desc: "Interesting discovery #171 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-172", title: "Curated Gem #172", desc: "Interesting discovery #172 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-173", title: "Curated Gem #173", desc: "Interesting discovery #173 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-174", title: "Curated Gem #174", desc: "Interesting discovery #174 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-175", title: "Curated Gem #175", desc: "Interesting discovery #175 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-176", title: "Curated Gem #176", desc: "Interesting discovery #176 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-177", title: "Curated Gem #177", desc: "Interesting discovery #177 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-178", title: "Curated Gem #178", desc: "Interesting discovery #178 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-179", title: "Curated Gem #179", desc: "Interesting discovery #179 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-180", title: "Curated Gem #180", desc: "Interesting discovery #180 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-181", title: "Curated Gem #181", desc: "Interesting discovery #181 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-182", title: "Curated Gem #182", desc: "Interesting discovery #182 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-183", title: "Curated Gem #183", desc: "Interesting discovery #183 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-184", title: "Curated Gem #184", desc: "Interesting discovery #184 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-185", title: "Curated Gem #185", desc: "Interesting discovery #185 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-186", title: "Curated Gem #186", desc: "Interesting discovery #186 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-187", title: "Curated Gem #187", desc: "Interesting discovery #187 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-188", title: "Curated Gem #188", desc: "Interesting discovery #188 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-189", title: "Curated Gem #189", desc: "Interesting discovery #189 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-190", title: "Curated Gem #190", desc: "Interesting discovery #190 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-191", title: "Curated Gem #191", desc: "Interesting discovery #191 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-192", title: "Curated Gem #192", desc: "Interesting discovery #192 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-193", title: "Curated Gem #193", desc: "Interesting discovery #193 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-194", title: "Curated Gem #194", desc: "Interesting discovery #194 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-195", title: "Curated Gem #195", desc: "Interesting discovery #195 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-196", title: "Curated Gem #196", desc: "Interesting discovery #196 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-197", title: "Curated Gem #197", desc: "Interesting discovery #197 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-198", title: "Curated Gem #198", desc: "Interesting discovery #198 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-199", title: "Curated Gem #199", desc: "Interesting discovery #199 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-200", title: "Curated Gem #200", desc: "Interesting discovery #200 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-201", title: "Curated Gem #201", desc: "Interesting discovery #201 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-202", title: "Curated Gem #202", desc: "Interesting discovery #202 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-203", title: "Curated Gem #203", desc: "Interesting discovery #203 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-204", title: "Curated Gem #204", desc: "Interesting discovery #204 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-205", title: "Curated Gem #205", desc: "Interesting discovery #205 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-206", title: "Curated Gem #206", desc: "Interesting discovery #206 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-207", title: "Curated Gem #207", desc: "Interesting discovery #207 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-208", title: "Curated Gem #208", desc: "Interesting discovery #208 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-209", title: "Curated Gem #209", desc: "Interesting discovery #209 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-210", title: "Curated Gem #210", desc: "Interesting discovery #210 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-211", title: "Curated Gem #211", desc: "Interesting discovery #211 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-212", title: "Curated Gem #212", desc: "Interesting discovery #212 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-213", title: "Curated Gem #213", desc: "Interesting discovery #213 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-214", title: "Curated Gem #214", desc: "Interesting discovery #214 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-215", title: "Curated Gem #215", desc: "Interesting discovery #215 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-216", title: "Curated Gem #216", desc: "Interesting discovery #216 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-217", title: "Curated Gem #217", desc: "Interesting discovery #217 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-218", title: "Curated Gem #218", desc: "Interesting discovery #218 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-219", title: "Curated Gem #219", desc: "Interesting discovery #219 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-220", title: "Curated Gem #220", desc: "Interesting discovery #220 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-221", title: "Curated Gem #221", desc: "Interesting discovery #221 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-222", title: "Curated Gem #222", desc: "Interesting discovery #222 from the deeper web archive", cat: "science" },
  { url: "https://curated.example/site-223", title: "Curated Gem #223", desc: "Interesting discovery #223 from the deeper web archive", cat: "art" },
  { url: "https://curated.example/site-224", title: "Curated Gem #224", desc: "Interesting discovery #224 from the deeper web archive", cat: "tools" },
  { url: "https://curated.example/site-225", title: "Curated Gem #225", desc: "Interesting discovery #225 from the deeper web archive", cat: "games" },
  { url: "https://curated.example/site-226", title: "Curated Gem #226", desc: "Interesting discovery #226 from the deeper web archive", cat: "articles" },
  { url: "https://curated.example/site-227", title: "Curated Gem #227", desc: "Interesting discovery #227 from the deeper web archive", cat: "weird" },
  { url: "https://curated.example/site-228", title: "Curated Gem #228", desc: "Interesting discovery #228 from the deeper web archive", cat: "interactive" },
  { url: "https://curated.example/site-229", title: "Curated Gem #229", desc: "Interesting discovery #229 from the deeper web archive", cat: "creative" },
  { url: "https://curated.example/site-230", title: "Curated Gem #230", desc: "Interesting discovery #230 from the deeper web archive", cat: "science" },
];

const DEEPER_SITES = [
  { url: "https://www.windows93.net/", title: "Windows 93", desc: "A fever dream operating system", cat: "weird" },
  { url: "https://noclip.website/", title: "Noclip", desc: "Wander empty game worlds after the players left", cat: "interactive" },
  { url: "https://www.notpron.com/notpron/", title: "Notpron Level 1", desc: "Begin the hardest riddle game on the internet", cat: "games" },
  { url: "https://www.theuselesswebindex.com/", title: "Useless Web Index", desc: "Deeper archive of pointless sites", cat: "weird" },
  { url: "https://www.geocities.ws/area51/", title: "GeoCities Area 51", desc: "Preserved 90s personal pages", cat: "weird" },
  { url: "https://www.zombo.com/", title: "Zombo.com (again)", desc: "You can do anything at Zombo.com", cat: "weird" },
  { url: "https://www.rrrrrrrrr.com/", title: "Rrrrrrrrr", desc: "Pure R", cat: "weird" },
  { url: "https://www.omfgdogs.com/", title: "OMFG Dogs", desc: "Spinning dogs", cat: "weird" },
  { url: "https://www.staggeringbeauty.com/", title: "Staggering Beauty", desc: "The worm", cat: "weird" },
  { url: "https://www.fallingfalling.com/", title: "Falling Falling", desc: "Endless fall", cat: "weird" },
  { url: "https://www.heeeeeeeey.com/", title: "Heeeeeeeey", desc: "Hello forever", cat: "weird" },
  { url: "https://www.eelslap.com/", title: "Eel Slap", desc: "Slap", cat: "weird" },
  { url: "https://www.pointerpointer.com/", title: "Pointer Pointer", desc: "Always pointing", cat: "weird" },
  { url: "https://www.cat-bounce.com/", title: "Cat Bounce", desc: "Cats", cat: "weird" },
  { url: "https://www.koalastothemax.com/", title: "Koalas to the Max", desc: "Reveal the koala", cat: "art" },
  { url: "https://zoomquilt.org/", title: "Zoomquilt", desc: "Infinite zoom", cat: "art" },
  { url: "https://www.thisissand.com/", title: "This Is Sand", desc: "Digital sand", cat: "creative" },
  { url: "https://patatap.com/", title: "Patatap", desc: "Keyboard symphony", cat: "creative" },
  { url: "https://www.boredbutton.com/", title: "Bored Button", desc: "Instant activity roulette", cat: "weird" },
  { url: "https://www.pointlesssites.com/", title: "Pointless Sites", desc: "Directory of the pointless", cat: "weird" },
  { url: "https://www.thequietplaceproject.com/thequietplace", title: "The Quiet Place", desc: "Leave a message for no one", cat: "interactive" },
  { url: "https://www.drawastickman.com/", title: "Draw a Stickman", desc: "Your drawing becomes the hero", cat: "games" },
  { url: "https://www.linusakesson.net/scene/longcat/", title: "Longcat", desc: "How long is long?", cat: "weird" },
  { url: "https://www.arewethereyet.com/", title: "Are We There Yet?", desc: "Classic", cat: "weird" },
  { url: "https://www.howmanypeopleareinspacerightnow.com/", title: "People in Space", desc: "Live orbital human count", cat: "science" },
  { url: "https://www.thispersondoesnotexist.com/", title: "This Person Does Not Exist", desc: "Faces that never were", cat: "weird" },
  { url: "https://www.thiswaifudoesnotexist.net/", title: "This Waifu Does Not Exist", desc: "Anime that never was", cat: "weird" },
  { url: "https://www.shadertoy.com/", title: "Shadertoy", desc: "GPU art community", cat: "creative" },
  { url: "https://www.iquilezles.org/www/index.htm", title: "Inigo Quilez Articles", desc: "Deep shader and math writings", cat: "science" },
  { url: "https://www.redblobgames.com/", title: "Red Blob Games", desc: "Beautiful algorithm explanations", cat: "science" },
];

const CATEGORIES = ["all", "tools", "games", "articles", "weird", "interactive", "creative", "science", "art"];

const LOADING_PHRASES = [
  "Diving into the void…",
  "Finding something weird…",
  "Hope you brought a map",
  "Consulting the digital oracle…",
  "Unraveling a new thread…",
  "The web is whispering…",
  "Opening a random door…",
  "Curiosity is loading…",
  "Somewhere interesting awaits…",
  "Falling down a rabbit hole…",
  "The algorithm of wonder spins…",
  "Preparing mild chaos…",
  "A gem is being selected…",
  "Your next obsession is near…",
  "The internet is vast…",
];
